apiVersion: v1
kind: Secret
metadata:
  name: postplan-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:txHJmmPSWSy9CpDFgnirPRIf0mLmdTWzafmwlg1qUtaQmmTRmOvoa8WI5iHxSgG+JlF5+5tqnvnc9NLmPzY/eyAQc63ux/Wn3YnSKVMo7p8jygV4txE+mQ5eLcJ0+1aSr5ilJmfuznE=,iv:mqLDphRYqPCcm5lGPiNoz16Rh2RyNlFarMir/EjErSs=,tag:Hx6iX+jTtyxn/mr/v1Okiw==,type:str]
  POSTPLAN_BOOTSTRAP_API_KEY: ENC[AES256_GCM,data:OdFmSf/m0SNsLgw4Yq2jJSRwe6kcUnKNJSL59V/Wfa7lJT4nAqN6,iv:mPuTWQv+R7aF5zBWR8JYjaGNO77KxQLj5CbBz+t6wOQ=,tag:0aGdBkHVLbk1IFaDnwwn9A==,type:str]
  AWS_ENDPOINT_URL: ENC[AES256_GCM,data:f3PoBl2zj4oA5n/D+vk8UBSPyODEBLJy,iv:UaGgq2axGG+sDTGUBm/pDILa3qyPDXUfcaq+5VmBAu8=,tag:aOcGJzw2tcsknFkfXu4QsA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:z79MYC524g0=,iv:L7su5CAPaq6xIGIKRkwdx+CYhsJzO540k4D79lxY7N0=,tag:gHSIo7mEg1b2zczMfMe3IQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jOM77WIrwMUpOcmyn8HASZORYjLkIrQ5Bk/VD1yv3C0=,iv:e+NVJLr0NiX50I88hm52h6CfOLrgj/f+nhYXggo+FlY=,tag:LdOHEIwpdoZqQ0BpyPm1hg==,type:str]
  AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:iYeQ7uX2RZ4=,iv:TqEfG4WWE8QOmQho9eRoB3cWVDv7bhj9C94uOTmLPqc=,tag:m/GDbqc3h8vk6qwcv2kvyw==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:iHz3eQaTPNDp,iv:vKiSHAkbTBiA9hQxrvE+zrvtcqO9wHvLRus5BMPRVL8=,tag:IZTm2zftKLGTePwa9Xrkwg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwblg3b05HOVBWQWtlL1FH
        S2RLQW8wVnU3S1RxMUo3Vk9CUXJ0TXl3eXcwCm55WXVFakhhWjFPNVhCWFRONEVH
        bysvMzEzTEFoRUFpWDdWaDMwSHQ1VmcKLS0tIC9rOGl0UVVhU1hOdjQ3U1ZLemYy
        a3BWeUNUbG5Pb0N2UFB4ME1BRG9mYkEK3wbep6E/EhlnhJCmUdVwoelsOgtH7Kl9
        7oT1j5ZBkftCgyn4ANFBzFqHZll70TcDjf/LWeyZ4AGrGAB3ZG5prg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-07T17:55:00Z"
  mac: ENC[AES256_GCM,data:I6818QfaUyT+Au4W7lbG51muLsTfQ1DML1p0+ud40rewBP7i4HsVkHewlX8yQkbUR01gdYMcigOmIREB59i0UM5+MUP9zvAjLumdZLyRfdU9OSWTeWmOz74ihplC0tlSy3CSIawsX4vqpa9MOtkX+/Fw6RTXf7/2F50qh6vrd0E=,iv:Ft+YDnBRWncIxfVjOEywu4683uA90ZrJtPWXw8SgTp8=,tag:JsyTXElN/fJdTytUBPLWhA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
