---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./network-policies.yaml
  - ./alpha/ks.yaml
  - ./beta/ks.yaml
  - ./gamma/ks.yaml
