# Authentik OAuth2 provider "code" (app slug code). Consumed by the per-workspace
# SecurityPolicy on the public envoy-external routes.
apiVersion: v1
kind: Secret
metadata:
  name: code-oidc-secret
  namespace: code
type: Opaque
stringData:
  client-secret: ENC[AES256_GCM,data:A3aVFY9p+6Yn+85Uppt+ziLusWc3HOHoCFUnmcCHnAqYi7ojmjtgJ7xrBMGgr6zgLx7QcH/ih2fm0mfOy6X6QDUlz8JPrRvXWx9py/muTXHrv3ufrMzHvjvXP9NHEScMiMfGouf/xUs0hCp5wBIl+QhvrVb1pwiXHIk4+ToZMME=,iv:JsgrElOvAoGK+prSgswgH4rnvejfJeejxsqVipa/pTo=,tag:dMoGyw/F/TZcNeD8VcUE1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N1NDSE5qMWplSFJZMXNS
        alI4TktqNS9SUlB3VlUwbkpTMkhRQ2V5RHdRCmhoR2VwQ2tQQVhyRDRsQmMxOFBE
        UVN4blBueUV3NlRZVEp0RDdZY0xNL00KLS0tIFN4TERjQkNFMkRmdmV1RXNDK2Zh
        dTB6MXhIa2pJV25JSkpSejQyNXd4SG8K7kgxwl+SkSVexskzNUILHerHSfpF3IPg
        wNf5mqBFIiwztcQo9PXSk+cxGnKzgVQ7vzFUD0HbAUnYuDyoE3AIpA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T16:29:11Z"
  mac: ENC[AES256_GCM,data:lQhSRxcX9FBniKSqn5Z05HUzdHQqYE9Or7wloOowGLaaDHDv0hSLr5ifCuJ2yQeRgOW2CdGZTAL50S4MkkfpKISuvq0kOgiaB8bnqNh115rBtWxR1c07ELankqd1+tfBBZZhHHj85L1DjZpPHj613bYjTyl/TMVB5/f+ozpYTr4=,iv:Xv7kmI5ENtZKciavzSPoUc7lbbVYa3bOy8UvCUjMsRU=,tag:WXY8WA4wpUQPlvXp8IhpSA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
