---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  chartRef:
    kind: OCIRepository
    name: uptime-kuma
  interval: 1h
  values:
    controllers:
      uptime-kuma:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: "2"
            env:
              TZ: Europe/London
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3001
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        size: 5Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /app/data
    route:
      app:
        hostnames: ["uptime.iacob.uk"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
