---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: firefly-iii
  namespace: default
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: firefly-iii
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/default/firefly-iii/app
  postBuild:
    substitute:
      APP: firefly-iii
      APP_PVC: firefly-iii-data
      VOLSYNC_SCHEDULE: "30 3 * * *"
      MOVER_UID: "33"
      MOVER_GID: "33"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-secret
        kind: Secret
