apiVersion: v1
kind: Secret
metadata:
  name: radarr-lowq-secret
stringData:
  RADARR_APIKEY: ENC[AES256_GCM,data:g4eFeRIPczw6+HRCMu3mBTwOxR2Qj+jFRFB5kLQL2EY=,iv:ERGzTCtvw2esghXIF5zlH9mHCiDKtrDIyhmPaaaT2K8=,tag:JHyi59hzkLlWdl4wYm6E5Q==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N3NCZkJxYmxCUU1wdGNx
        Vm4vYjVDRTRVaVBmR2FpQnBEdEtlVzY4ZkVFCjZpSEQxVGYxL0lzdkZFMXlkbEpw
        UTQ1SzcwbDBWMk9qZkl2SktBQ2x3blUKLS0tIGlvT2haeU5mN05Xay9hSHJrOEw4
        WUNVOXhBc21pRHpZTEpGb01vK1Zsa0kKw8ZahVadNj6b3JH/StLkmlcn7f12X9FB
        en9XiM6Z0lyAUod9KVwrguLUijQsyShh8mk/2RRKEtGjrOnQjaSKSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T23:01:22Z"
  mac: ENC[AES256_GCM,data:GWknmh36Q1cXmsH7OyzFvcx4bSQ38ySauWvpvPCnYhbg4E9GkPNLOHUHg3eOJGGl4dtLIzM2rWHr6IElmnTs3z3JCbo586Apkp6baKfSve/hA1Um7iXnSjObW5kZ1iIYO2UPOjDxo/HxWQ/aqaDZpievFhwWdfbdwJ0atSp74CY=,iv:ghMb52VHPa0xFfX9A62I5eEHVtF7lNqOFJSyEUV1jPk=,tag:CpX8O6ytI5qD1JD8haDFIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
