apiVersion: v1
kind: Secret
metadata:
  name: radarr-lowq-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:WvC3SuoeD1VlnZ3tD9EGkHmICl0oG7NfAj9Q50rT34g=,iv:VAE4erOgESKdbyw4eVzxID6m00ds8sUsl/q17MD7xR4=,tag:vv5vUgqc39YkJAC6ys/14A==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d2FEQThLVTZHRG5EZnFa
        TlNWQy93UTBLQWp3cEN0SDRCd3BGcG1QMWt3CmVLMko3aFVmOTg5NTZCYWRtR1ph
        aldwdlU1YWNHTFFRcmU2dDUvc1VlcXMKLS0tIEl2SXBXVnM3aldiRlpTUkNGY09q
        dmZRbVZOUVhVQUx6eVFFSnpISTVaUWcKkUAH006mfnwJljKT7CVqGGFhduM+U2sk
        s8Phx3tHVmEGjgzrpDEhOUeNKP38i0zsxsAv5O6WXaOp2QtGrxCgOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T22:46:00Z"
  mac: ENC[AES256_GCM,data:8M2+mHw1+oJMWHPLHDGCJG/kD+Hc1OaPS1TGWa1qE6+IJFvRjruyfh/P4ADxvzYJ9osUNRV4nVgL3rOqegk9zY52sqwUnDPouXdqwTEnhbSKDYMyx2KyPuHEiI6J8I4/5088ZO1VCwPYFl3iWpFMyx4FQfdd+wdaIzyxx3gAWqU=,iv:dwPdbFRjeEMJX5McYH0MFg6a2LHXa6SjMNEekQRIACY=,tag:Piv9BRwzQNR92KQX/ac3jA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
