---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: android-emulator-scratch
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  resources:
    requests:
      storage: 20Gi
