---
apiVersion: v1
kind: Service
metadata:
  name: android-emulator-loadbalancer
  namespace: default
  annotations:
    lbipam.cilium.io/ips: "192.168.1.15"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: android-emulator
    app.kubernetes.io/instance: android-emulator
  ports:
    - name: adb
      protocol: TCP
      port: 5555
      targetPort: 5555
