apiVersion: v1
kind: Secret
metadata:
  name: planum-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:OlrehI54/q+SrB7XokZucMVp3uuPq2zbfxWywuFCfMvdx0jLymO+CIl48bqs7MC/tAaJ1A6jhyzWQ2++HnMrpR4R+2Ryi+fSoGXMDDbzRL0sUNtEeIzbakaX/seiixZ0TVVgfc2B8CHdu0ykw5MuCxfzmLA=,iv:ArThmjyD18vLxMEoKukx7D8f3hjx1/WhP8o+jjdA7g4=,tag:gY78PO23zDgyJXwWvqakJQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:APtA+ou/FrQx4zVkdjrKfqbm1lkit/h/QKYLSYP5y5J43g9qeqwZtqmsreyF5LVeK51dtMgtE663Q/Mc3OOJ3w==,iv:uq6w9u8eO8/UKmJ2VvyRZwy7dnXO4Y4HDud8eHNBY1o=,tag:15cU9IYQEDwp9ttqofGQxw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WDNUcVVQclVlWC9xUzdH
        VzBCeGhPTi9IMVYrQjdkbnhPd1FRNUwvcER3CkFkU0VPY3R0VVZLSlYwR2R3SnVZ
        blBDTE52UmpWSERXSzM4RDhUOElCY2MKLS0tIEVpbmJob09IRU9QY2o4ajVZNVRQ
        eWgrK0JlRzZsaldPODUzMWxEdmNpU1UKk1baBMNlU0CTsG3UByvyGTCUbyG1yFsC
        cz0zerHHRiYIR8Dj49eBU6PZJnUwqSiHmH56KaiyVsIOsOGD3qjpQg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-05T12:58:32Z"
  mac: ENC[AES256_GCM,data:H/Rr0H9IuBnRgDEl/JEBGvZXLo0ZexakHYiiQOSaE79uymfI+ZI1qpmxexXrJ/wFE0w7wlVOmGtgXajuMFKMe2hOOL80JPz2APZcdxX8rFTu46HaJe75zMmwW3AbQ/tKFWXVV4V7rbRGovV1cdu0el9uv/12rpVWXNHF45sh/po=,iv:eP2BEYms0IMWCjX2VQEO1gF6a/VSczQBfhA8BVDiM5g=,tag:W2YAKjx3z2AZQ/TwQJnoBA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
