apiVersion: v1
kind: Secret
metadata:
  name: planum-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:gzsD3pDx/2MRj87CPW10p5BuTYQM9OpaWLr3pt6SCDpuNmZBw31/QJkL6/vIupeTKP5VlvqKhNbNwF3CSvH/dU5iw5Jxn5r44dbGNESkFyvhuZ4GKKcd91hwyigbufUBepKnXJH4mjDRLoeyiYy0PBEOpMg=,iv:MLPhBaMdoBknD42ekcWJyB460Z3er7dp7VdtShm+uX4=,tag:U8unIFKOVXFc90ADLInP9w==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:d0LT05EGhTB3HBNI0EeFciTOTPGN8Y1lJHNZCg5MWgm0U8iYQfVvjI4xlN769BmdYg4gto1NrMCqzGpR6h36SA==,iv:jab4nBqrVxveUbWP8TQtsd27HG/8FOBzYF1Qn44wAKI=,tag:2IjopSczl+ud45iATFbC0Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUWRwSm5hZmkrSGZUalBu
        UXp2bDN3Wnp0UlNhaldlRjJmRGpJckFuZmhvCkM5Rkd5NWpUNnJmSU1xTWpqU2Vs
        NDQwb2hmTW0zSEI3Ri9oQUNveFNZMGsKLS0tIHdjSXJjOFlqMnhJVmNxcFVjMFp3
        UzJMa1BOUzNxWnJHV2FiMmprWGU1eFEKeoN8rbEGHFsuQnXVQ2eoudjjmHvphpmd
        Ew6bWSNe08JCcxSvN9WRnW1MORxd37IJNS3SX1yu0fXsG45qFzKrdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-02T18:17:20Z"
  mac: ENC[AES256_GCM,data:hXopXFdgGZuI95WJC6Kco6ovz1A1gB7M5s3ownXvEfwvA4B3fYfo6Q2QITk4XSPhjvERp5F8TCTHdUWnVoF0TaLzOCskHVBJYQc3caYa/qur3IWrvn/s1Lser3m0DlhqzBAHnqM1FxJt84VXrGnaQ7ZQSbwkh/t2rtj9XCugxmk=,iv:oLwK48bxx28SxPygaVjJh+dF4lBsThjKqnSAmYNZ/NE=,tag:FUPxj0zkNftNXDC6CfwwoA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
