apiVersion: v1
kind: Secret
metadata:
  name: shlink-secret
stringData:
  DB_HOST: ENC[AES256_GCM,data:/xKHKEMO3hZ0/CDiR2rzT1AlYSoGOWheoUCvPiBVy+mUgY/3,iv:nQ50FIqfLsWyFc9VDbcgfRD8SefvOb8yqlMFzZxP91M=,tag:jjYgGFRvffUsZbs3hsztew==,type:str]
  DB_PORT: ENC[AES256_GCM,data:kvK/Ig==,iv:FUkrJKhoKoBzO5vwwB8of/blHMhFfN7paJxRArNV9X0=,tag:gnItJKJsWjAQInwYRpfuTg==,type:str]
  DB_NAME: ENC[AES256_GCM,data:C75D9NTy,iv:CN1WfDVlTrpHv042pwmlT9f4rNsyTiFZp6vvZJ+Hies=,tag:EDBEdhwQcy40ECzl4IlB2Q==,type:str]
  DB_USER: ENC[AES256_GCM,data:iFtlEQzq,iv:yYnNfzlZEkYa0D0SIBZzG1J8TMZjlvWNrj4IyvTwmhs=,tag:SYkIjxN0WSDyBY5fCHnKxw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:TnVQOoLpKACivJSwuVpXKXTaBmfaFTi/acpdeF7W9Q==,iv:kxElQJaLO8009b29AaswE2v4b6DjHrcj5N3x3gD1s9U=,tag:g/2xovjUvh/Ksm1yjByLTQ==,type:str]
  INITIAL_API_KEY: ENC[AES256_GCM,data:18pkyoyXEfnI09ZlVUTh5CzRXXI4BqqkxuOSJXxr/lYJoL8gNjQMHxiJTd1EtPVAX625RzGLqNCUGSdsEa7+zw==,iv:keleiBNhRZW/3CO+VBflbeQruv2OAmuyY6mLFzm5Rok=,tag:xzx9dSsZxbto7B/CvbIkDg==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeUJFcmY2QWh4a2haRnFh
        Z25neEdDTnlaWXVEbDZ4RlJaUFhWQ1huN2dBCkppMUEvTng1MFY2R1RmTllzTFR3
        eTZkVkpTTUNYd1hTZ0h3VzRnM29oT3MKLS0tIDY1VnZFbHIrM0FNVjMralZqaEpL
        RWJMRHgyQjY2S2NvS2pHRDdLZ0ZJNDAK0N1QKvGtLy4Ewn3+d2159stMhTuzMN6F
        I4wbdb9EX0hoW9qqvIo3/8PzBpQqCGFjR8hRYUlXOVXkdKwymntzUw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-22T20:17:54Z"
  mac: ENC[AES256_GCM,data:hLbdWB7Cyze465JS9duVWWrzHCymB4GtwAFp7g5BZKghGEoxJc65XZnl6M5g9BHPRwT2Z/KGBDUi9JCyCC4mRn+dZ9LVXCBh70BEk1qH1NccrEAMtRNaieqqh7CgK+XGzQIbneaiJ7K51FKPQgMRHp25hIhs2kfmQ6sVD7g//Jo=,iv:hu0iyPy02zMqrdLuoJBk9Wik/58eiSfQOiaVDJvWQPE=,tag:kPvTWCEp0vC5YVJFFLx35Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
