---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-server-workspace-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.10.10.3
    path: /mnt/SSD/code
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-workspace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: code-server-workspace-pv
  resources:
    requests:
      storage: 100Gi
