apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
type: Opaque
stringData:
  PASSWORD: ENC[AES256_GCM,data:P6/MrNCrusM5vXYSeegdMndGqaU=,iv:S3hJmNoYdvEQxiOr+YwC4JiyDPKVmVySriHFLH3sMu0=,tag:GIgv/mNO/KVpPKxMI8iiqw==,type:str]
  SUDO_PASSWORD: ENC[AES256_GCM,data:6788E6RAMQZb8tvTbVgLXDmx6w4=,iv:V0tKsEh5cggNLFwoZGc2Texuac8NaeNDFnGo7f8wUD0=,tag:6scnYamHJNuJQ2k2OnNeQA==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMytPcFdXckJncWZ3V3ZC
        UmNPQkY5UWNDQUpFWjBvZzhaVVg3QkdmanpzClVrYWJSNUhTcVBuSXBFUUZtc1dY
        ejlwd3g5RjVDQi9XZVl6d2pHT3BkM3cKLS0tIFQzazk5cTFoSWVqdlYxQVFHT0pj
        WTNkWVZLa0NtL1BpTlBHOEZHOTEvTGsKJwFW/mpfedECZ+Obb7DHjwKshL9Mx/kR
        i69+MsQbew5vimhMxnsn/80zALSUltHS3ZgjIxRS29wmCZ13kin4Iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T10:47:16Z"
  mac: ENC[AES256_GCM,data:g8adNiJQfHAp4Q4AR5XIP0iqGjqpTG5NnZAegGPLUV9bkqBMwVy94J98quVPNBXZr5cNQFbfM+HaDu6bNt1oevX2rUGRxUqB1/VzgGbgsqE70eLrrlCa0TGILCrlPTeC9S1PBttejCyK0q1/7/ruI2qhv+r8WxkzB26Xpw8ZuCM=,iv:hEzYxxc71bkFAPmUe84YBcLJpZwsfWEMHKbvBfZAL3Y=,tag:19E6cW0HVRDobo/0VRuVnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
