apiVersion: v1
kind: Secret
metadata:
  name: fanwatch-secret
  namespace: default
stringData:
  ILO_PASS_DL360: ENC[AES256_GCM,data:gLhcEVqWAdw=,iv:8kjtks7NtSLFE0y23jWyPaGbfAxfszvoWFkn+sYddJA=,tag:5JO9KzDNKhbdk4nXYVmT1Q==,type:str]
  ILO_PASS_DL380: ENC[AES256_GCM,data:ICzYnG/kEy4=,iv:ZNnaDG8bpNHgbAwf54/9Aq3FpXrnfVD4/vdY0RIppjk=,tag:M1DQ4K706wcLJjVAaiQyVQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOGx0Z3BvZGpybldtQUxY
        amRyZ3hhZVJ5VVZtbGkvT2lVMkg2eGNIbUZzCjZtRlA2TEJ4aGpSUHI2TGtjQmdp
        Y21XL21RT1NtYmxzQVRsaTlqWi9HUWMKLS0tIGNKU2UwQ241VkNudklxR1o4MnlX
        Unk0L3VFSWpWZzFoWlI1ZVR1dEZxWGMKqgRIvfj+F7X+kEW1F0tBDxuTGIHpKLZR
        fdTjPfZpW0KnBt+LTm1Qhko40lJ4CvYWxpkI5X6E9J/LLOhm6Batog==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T18:35:47Z"
  mac: ENC[AES256_GCM,data:dZnKQmRnMxCEpLX/pqYDKwSCFsVl181aKqw078ACDmRVKWN+YhnJ20IWY6Zp6F6gMddX4H+b4FtZXGtW98B5i6iDd9VSb5WpwsTZCrE0DELT5UScV1Y0oZLMx0I0qgrlcc64IF6y5cUNM8d3LpfKGrsLZBD3dDTPEAgjg5dxwkA=,iv:M2DSw4XRKt+5zoHOUuNGbHu1vgauZ8GDOv0O246vK0A=,tag:ZpCRy+pcDK2/wM+M/eJusw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
