---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrutiny
spec:
  chartRef:
    kind: OCIRepository
    name: scrutiny
  interval: 1h
  values:
    controllers:
      scrutiny:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/analogj/scrutiny
              tag: master-omnibus
            env:
              TZ: Europe/London
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &port 8080
                  initialDelaySeconds: 60
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 30
            securityContext:
              privileged: true
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        size: 2Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /opt/scrutiny/config
      udev:
        type: hostPath
        hostPath: /run/udev
        globalMounts:
          - path: /run/udev
            readOnly: true
      dev:
        type: hostPath
        hostPath: /dev
        globalMounts:
          - path: /dev
    route:
      app:
        hostnames: ["scrutiny.iacob.uk"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
