---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr-lowq
spec:
  interval: 1h
  path: ./kubernetes/apps/media/radarr-lowq/app
  postBuild:
    substitute:
      APP: radarr-lowq
      APP_PVC: radarr-lowq
      VOLSYNC_SCHEDULE: "15 3 * * *"
      MOVER_UID: "568"
      MOVER_GID: "568"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-secret
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
