apiVersion: v1
kind: Secret
metadata:
  name: inbi-demo-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:dafwMHX6xP8B/bYXB2hJLtmpKI+/DJHnJf3+lefeAUPQ0fIDe7l57A9Y89tRiZJGkKm0v0Vdt/rGwA8AYJ5eGQ==,iv:pR1QM1mT4iT9EpPDOBkmY4TlOsLZH2+ALxkACgtbILI=,tag:RvAiaLzcaRk0VwIMEFmkQA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:KkKs8hLBb4Vmok2BkE+aKt7JJ3o/7CFrorMfvXijFsP+JDX34bqnmSHedBPCvd3MmI2a+/JaXLkOR7svluXMeABEGCF5pA3K5A0iCJ8AHkGcXihhv7x3Vps1ds0UzQeXyW9N8n8KbRm7mtAOOPAU+1yD2a92vG09Z1JcmE+sRqvo475fNTmdGw==,iv:gSgmm2SN+a++JvPY6JFL5TGnY/33iGwpifZvOIZYtUA=,tag:jtm52eF30NzMTi1aP6QVUQ==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:n3DdCNhP5fiO5wIqu7ILO3aLEHtTQj9TClQ2g90D1WV+YdJRGp4Pq+G3Y2MUkszlI+aVrChP+wXlaDBqfWTiLg==,iv:NnSoE4seYXRDYJh5py+0eHCHonO5d30qzdFa/ArktvY=,tag:Vwj21Dzd1y6DxMnJ8AaHsA==,type:str]
  JWT_REFRESH_SECRET: ENC[AES256_GCM,data:HxgFnC+tUHFc3gzp3NxaW5hQ58n5ZS1mDk0EQKbHdL5Ke+qtYD+QDOM+2Vtg3a52jBZMUHpOHUfzTxfC7HjipQ==,iv:mJfd63hmTgbqKS4uGgxlaX9bgBlkICcsVPxHbb7vZl8=,tag:ka4h+gBehrxRpO+geL1ZDg==,type:str]
  TOTP_ENCRYPTION_KEY: ENC[AES256_GCM,data:uqxc58FR0oQ2tD2WSav61tdMgn+OtWVDtmb9AbuWq0ExvbU/0dWyqMSm+PKtAwutslylozoB7700uN6N+BtoPQ==,iv:/WmpDGuFETHb1CNvDjlUTHBVVjee6/p/PeijX69PNSE=,tag:tQtaZwU7ceOL8sYxjCFDdA==,type:str]
  MEDIA_TOKEN_SECRET: ENC[AES256_GCM,data:N24L97b/oPiDRmQ83iNmD0Qr6fjkPSmvkLFIiiqSj98sMozfNxTftvQlLoUhuXOnt/x7dJ9Miw+7/HXFRWRFug==,iv:qQ3NAzO8F4dWe1b5l3XsuEc13SuR4IADWKruKoZSLJo=,tag:WncQhSKEhwfkCKAhzBkRUg==,type:str]
  SESSION_COOKIE_SECRET: ENC[AES256_GCM,data:v0YmGtoINXnIqWhDzyHod9pcT0fYWeqdf6qYHPstmVlO24qluUk5+4bq6XQoTqukCyZEogc2CssesFFur7V8eA==,iv:Cz+Irm27EgykjOSApRo36TazBxYbX7KhtkbbPpS21fc=,tag:PLIQQF4IPHyRnYim/0QPtw==,type:str]
  DEMO_RESET_TOKEN: ENC[AES256_GCM,data:YmZPErR4Lp9NIxcoLUcJaQmz9GBUYyxUk4y09o76GGAjFMLGc4mVDocNku8zb3d20RehEKwZhwH8ucs2ZXt7Uw==,iv:c3bRmCM215oo00SgDyUOFJ1dNEQ+WyuG/qwNUQncWjs=,tag:4EVXvM89J8WpIkFDfZ1Ldg==,type:str]
  DEMO_OFFICE_PASSWORD: ENC[AES256_GCM,data:UlEmKbP8ReA=,iv:6GdrYSkbWfC5CbWn351ZFaHt3pafzM1QuenbER4wktU=,tag:OUJVEAbTDVtmrPybnKSaow==,type:str]
  DEMO_DRIVER_PIN: ENC[AES256_GCM,data:H13XSg==,iv:xtYiPmgVBFHpI24NV0uS2cqeoSX8Ld5L1AJBnFGYoQs=,tag:nHe57hv/Ee7QwKp/YNa5bQ==,type:str]
  MINIO_ROOT_USER: ENC[AES256_GCM,data:To+lhAjzRcduUZ/LHiYYC7u9Ow/Egg==,iv:IcHS0mOTXstAYn1eE6D2qmssu8N2hUL03pCowjYSLvs=,tag:mElGpu4xhFJ46yp5wa3IDA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:hc2JrlgNfyZz9VPo4jHbio6ykyMxxzO1UyRjgp7UPtZowxrTM1I4NuUNWF9yIXewy1fC/HCBpng4MByZc1RcuA==,iv:PCCQqHUf1eAYLhaYa+/x+dpLO/eZhbfNcJgm/geBit8=,tag:ugHw7KpjMIoC4tCHO6xPOQ==,type:str]
  S3_ACCESS_KEY: ENC[AES256_GCM,data:KYzF3NkHhqHK+IE+DAA4tY0W+ro5pg==,iv:PoZA2U8IdMnWDt1ljF4kCFNHE+ZMASDfnr7ekREMTp0=,tag:3HlAE4PLWzLASmcyBc9ieQ==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:WJkZrtwFTshwTdXctZFim0obI9eu7tBrmLwFV9TZFWHIXvU/EqiwPxCv2h7qmmMcJ013WiTYVjPnFbx2GOZ7tw==,iv:hp7HEdapq6Bm7ND9JO+FJmefOzwnYXhWBbri/yggj2Q=,tag:tqZKxPbgfrUUcDMo30Z1Qg==,type:str]
  TOMTOM_API_KEY: ENC[AES256_GCM,data:ysPuc7aMLxwyJk2P6l3rG0MwKAbnbbMpKl6aFCnhZsw=,iv:4mwYRPNvk4kjssYdPaVZVnar4R351y0sYvlR7ImbI6s=,tag:9eR7L0RIJXKp3Mfg5MEvUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob3BVZk5RYU04c0xadWhS
        eHJKVWMybjdhRGtHZHQzS1F5Y0xpKzQrd2owCmVrVldlVzFBNSs2SXNoVTBPZHpZ
        Q2dmZ1Z5dVpkOVRISVZ4YS9XdFVRSkkKLS0tIHI3aHBlMS9tSENYV3krQStqOGxw
        OWwxbnVRdFRmV0hDSXBUVXRWdEZLS3MKQHen5s6qbzD8XvG+6NCJS9S75ZUoCFdc
        rUl2WWb1xyYEwQskeQ3OBsCFz8U0VxdnCfZ+JBQ0OOrgBxSLq4M96Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T18:10:03Z"
  mac: ENC[AES256_GCM,data:4zmQD/o82c5LNsIUYElMFlREjTxQK/wBBn+73vXkz8hU9CrCk9Jg9nT3qLw085c4T1aPkZMZSLMZE5RyedvUZ9uemxJxOHh9L+P/BV4zkgyd+csZ9PIm9iKfS4uaQUnx/vvRmOH0W7FRHfQ+3dlaGs3wHJKoCf/4xT6vBC563Ss=,iv:WyaUvf7rTnqVQRYY8wWvjfmPAnYUgb7YGaogpAbkBg0=,tag:npg791PUOkpvogk/HHbK2A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
