apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-metrics-secret
  namespace: monitoring
type: Opaque
stringData:
  HASS_TOKEN: ENC[AES256_GCM,data:ZyIJd70/a4ShC7uWrAe9/htbXD120Js94JE7ko2mNTfNNQDAB03Rf3e8SGVjZbQjGYsGLOIFOdTAejDSavyENS65Z50/9yNNbJLG6o6Xv4wNXS6cHiZHTC6fbp3mqL1F2+7V+iGMimmxeK8Cpq4CxogV5wZYS3dOjsRFPHQyJygOv9eERtDWlh3Z1VgdJLXRenS05/eevuQiMNqQX+jJfsyigNUVQk1urLEwUSnHyJegTyJEMXo6,iv:9j9NywIzNgukyuFOwboD5oaMEJOVVKO3SYOPK3RvNvM=,tag:ym4SaBGfLSJEUN6cR4ygMg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyakNjaEpCb05yVFp4WENJ
        Sm8xcmZrRUFzTTdqT1lYT2pGaHY4TEZsbHkwCk9jUWtPRUV1Q1N0S0xpZjR4MTNF
        ZklwRjZhUWtraWpuSFVoWFZLMDAwa2cKLS0tIE9qK1JpUVlML0Ivc0tKN2M4eVlm
        MnIwc1ZnQUNLNU41RitwZllHcHhlbGcK/A2GXtbiAYGlcijqBycliR84e4ub96w9
        WVcEWhK55g0fw8kVbIJXOC9gbtkYhJB70YcmXYqjHv06F1/hR14tjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T18:28:17Z"
  mac: ENC[AES256_GCM,data:WKwDU2EKCHfzsB8ZrGIeFUfskgKXrMoWxQhVNYdJAaA0tautZHZ9tyjpG3CxtfeXe99N3hniCGWWyrdg4DFyMr37UpkzaxdXo42Chu/3C/i8h+8RC17RMeSxOLHekSgFtx31JRzVSGGIlV1oVA9meT0JS/jjzgZNPa+KVjqjk8w=,iv:WfvAXhc0j2mc6zjvJUq3fN6pe3ZdiBRChctZ4kHadWg=,tag:0NVLWEwJ35SQGaeEEya2OQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
