---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-lowq-tv-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.10.10.3
    path: /mnt/plex/media/tv-lowq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-lowq-tv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: sonarr-lowq-tv-pv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-lowq-downloads-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.10.10.3
    path: /mnt/plex/media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-lowq-downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: sonarr-lowq-downloads-pv
  resources:
    requests:
      storage: 2Ti
