apiVersion: v1
kind: Secret
metadata:
  name: sonarr-lowq-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:4AA4dwAuo8O90fa11+ZTVtzhjboGA9TKS4iIGm5XUz0=,iv:AxP+ZYQFZkwldKsGaW+PGeUoXjjJhR4NJVAq8eItCfE=,tag:ZomK9oC10+35o/R7PUPhuA==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaFhVbnlPRWdUdlpQTm4y
        bm1PTDN3Si9YVTBueHk2WHViWHVhdUl4Mm1rClJnVlRXTWlOZXJiWkc0TTdYNzFn
        dFhSRGhkQTBzaWdXNlhPV3BTeDR1SmcKLS0tIDdqQ1phemxlV3JLNU03NnRKaG9x
        VlYzbk5BbFRjNTVhWEZJbFV2c3lkcWsK0VmTB6wi/7FDN3r64R54GKvxX9X5YMgz
        XtMhkK+by/x2QbEcSoOf6JD2UBZNGGMJ1bpqKmo7tuFJdZrZr8jjVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T22:45:59Z"
  mac: ENC[AES256_GCM,data:Vt8HFm7Pz1gDjNWZ2oX/zN9PR2DqAt4Jm8jEQ9H3bW8V6zXxzhY9LQgQHD1SvV1K0THKN+jfY3GB2MJPdc17H3D2sdXD2IHL+OUTpZGFOTjTi/x1Fhmiulssw7Zd4IbbK94ksAL9cMyrb/KwVNZL+33s+ZoQv7t49Tni3QzwY8w=,iv:mAg5Y0DuvbrfyjIRWar09nJ2qJIdDfhVh7/1L01Afu8=,tag:4tYHdeQbn5mjhRo7w7YOWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
