apiVersion: v1
kind: Secret
metadata:
  name: sonarr-lowq-secret
stringData:
  SONARR_APIKEY: ENC[AES256_GCM,data:1oQw4AkEz70fL17fjv3G9QiXuhgMYAxH4vV/4NAtPas=,iv:RQqLv5asOWrbN+w5TPpEjBaP24Cf9Ha8tXjmwEPtUy0=,tag:vst0p3CozaJXn/DtxQZoxw==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWVdxaVpIZlU0TXVCYUlG
        b1FLZVJUUGZtT0R5ZDlnY3BqdFRoTVljL2g0CnNUY3dHSnR6ODloaDBoZHA4eDgx
        K2s4dnhTeEtVUjdLUGxQbWduTVg4Vk0KLS0tIHFlcVZRN2taWkxqOHBYbllqdUZm
        ZXBDODRZMDB2MXo3WGNiL3ZMT2IzWVEKcNPFH1f7Efw6iDJ8BlxujE9RAxutW/vo
        moV4784rMky2MjfAktiCYCCY4PjI9b4tWNi5a9sYHTZJjI/doKMCOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T23:01:21Z"
  mac: ENC[AES256_GCM,data:OzEoUA+Y/x4ciRiTz895eC86+2FKgOUfNWcMT2eYd+ffD2uS2zhSs11QMuHBi070eTmoOImPgMiNZjXQ4zJmC0RXESgEobrhuT1wZzcwNzMNkCIANj/qilBwThzaMCxt5CJYmfa+RJW2Wn1NZ8UY9GOGY6oOpfhDD2gE4JGnXg8=,iv:y56CjMZvfGoo3+bX3EZYwDRu+ZtYZt2r9fPZCdO6Gg4=,tag:80vv3nXriVt2zPjcdAK7zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
