apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:PhRr9KVDvmMLjmabdK4Rt03YLbpTGbAQ0dMjiRAYWSf4zWif2QEtPQ8mQUSbTlr7rFw17xiTQmpmmO7ltfaCRt8xWMyZ0hF/5UC9fDPLGmyPhH/8yt3uKZAsh87EEBDswhKcrCS57ofgsC1+r2uoOkoYwOpikurXKybnYEtF3Z4n6yFac+lrv1myJbmaQyO4oEHuRj2UdoS/0k0rhfNMUy3vgh0+Vp/T2yf/ThTgz7KxwG7xzmrzxf29vg==,iv:FmduJ+sNSdegvqdApMBw1z0Bpoy8Im6TavAJnSmxJ7w=,tag:fTPYy8BfJifvLLueb4W/zg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteFBYWVNzUHAvTmIzZGlY
        TjYrWG1URkMrenlnNExhclhtZ2xoK2poNHpRCnBEWENBM2c2Yk9aNVV6OWs3N3pO
        YjZsUHlpY2ttNjBsN3RGQ3Z2UkhmUW8KLS0tIHN5b1gwUDlYKzlXOW5BNXNGMmhn
        TWtUN0xkY0Q1MHFxaHV5VXJVUkZSR0EKXQ8LeP2Pf3NwWVwgcEnlV2hbYmoJhI3E
        hIO+gQ0D6n+9pJXpYdkTdOGPa1xK3w8cvha07UT0stKBlTHrR5n2Tw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T19:53:31Z"
  mac: ENC[AES256_GCM,data:bdgz0JnCRCbn2wk+D57cDwllyQNTG1VcYfcoDbnV6gqo2qj+EEI/gKkEN1YDE9ct9gHoAJ77ePFYVW0RaK0QikDOAjlAzGUdTRxhTJZPCXR7ZMJNAiBgRHRlY1k2r63zITQKN54/WVYqRj1Krgx7loJIF1wj3oq3c0julM/kOXM=,iv:ong5cm+m0QIisNEOyLRv6dIfE1f6hD6wl+RLFLnliOA=,tag:Go7vGUQ5s6w9DmvbDK2LfQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
