---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: petkit-snapshotter
  namespace: default
  labels:
    app: petkit-snapshotter
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - hass.iacob.uk
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /petkit-snapshots
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: petkit-snapshotter
          port: 80
