---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./pvc.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
  - ./servicemonitor.yaml
configMapGenerator:
  - name: petkit-snapshotter-code
    files:
      - snapshotter.py=resources/snapshotter.py
      - index.html=resources/index.html
