---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petkit-snapshotter-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-data
  resources:
    requests:
      storage: 50Gi
