apiVersion: v1
kind: Secret
metadata:
  name: petkit-snapshotter-secret
  namespace: default
stringData:
  HASS_TOKEN: ENC[AES256_GCM,data:VeWUcVtX3ZaPKc7dadoOPOVhdwED695FMJ0d75Yz9W1GYLjksq+WT5Hz5U/5/9kfYbFxOJ9OEGM4RXm663DsBudOxYfXzF7GCzY88s9PHFmnS+QGOTHTlcNxXbAv8CqYaL4eQdGhtRrqeWKTE4JTJLs+/KINDfMepEkX/g6Sg9Dp7JCLC2zj8YpRoCHjGRtrjzrt5zyLS3tyFxUQPacqq7zuCj1vj1HGJrCq6HPONTP5YBSiTz5E,iv:HuxhLZw5y2qebpnXO4jFuiFcXRRgR9qBfxGHQbsCIIo=,tag:4gkVwLzB8a6JrrpNaoX/xg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWmtwZmF0aEhZQzZNZElm
        Rzg1WktVR3BYbkk3VThjRHhpK0pjQnQrVzBFCjZlSnhzb0hYa1o4RUNjSDJzSXRX
        TS9IM25ad1AzNlZpaXN5U0lGNm81SEUKLS0tIDYxcFpqOXJiUWV3TEJ4VXhyUmNB
        L0k1ZS9hK1A2NDF4SkZ5eEVydVVmekEK7T77QwbaJaGuMOuVB2y1dpxFLLjcXPYD
        44pcAxOg5uzlYVRxcgzq2Xah+i/mGmU0cFW1rkBA60mDVsSDLUw7Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T22:39:37Z"
  mac: ENC[AES256_GCM,data:vGNnzJD9hmg/ZVaevgEgCkcU4j2Sy8G5Dcq2P1pQxSI9XSwSTt32CAN337UObJZ18/ZO+/O6zorcSQrj7HWIrggDok4dLcD9FWvXyVUQ2inU/XLi6HkXD8/HcSMGWE30Ctx4n1utoTS7wepWrmKcc5ZWwafSuVJk5ydLaUa2c1E=,iv:iiDew3mK1/7rbQIqQHngcLPY/wF370hmNwN0yntEbwM=,tag:jhwBjY2RmaS5Iat+HoXMgg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
