apiVersion: v1
kind: Secret
metadata:
  name: renovate-secret
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:IilEWk1dX4+j4ojhIm4BFg6ur79/2BBmOXyDHAR1WLyqdiTl7ZPvIg==,iv:46ETt+HzNlgS6nFEEGkYxoPHMt2NWshZuWpoQGDOyVQ=,tag:xwCLiZvX31dflFBet0LkUg==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:qGKTX1E6aWb8u5L+8UHiZ7zBLXi1a9Mjj3cyJ+jwSDOPWPtqAc8iRw==,iv:hWvk0+5E0bQ6xfUXuifenpXRQfbBa/Mwuvmjg6/ETu8=,tag:pAd/XxB7hBuFe50kRad4kg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTGdYZ1VnZmZVWUx2UjYw
        UElJaGMzdm1RTjNWYnU0Vmp2ZWQ3RzdPemhNClBUQ2R6Z250TExuUXdxc1Q2K1Fa
        a0hZYWZwejRoSzNFYlMveXNyd2lqeDgKLS0tIDZheGVlM3l5a3FhakdHTXUyaDVl
        b3dXUWpodkxmTEoxcEpoU093UmtrZjgKFnjfiAqhGvJuKOn8YJ0iknaQtt1OwnpY
        Jf3npT2JAheTBxer043l/rtF7T0pj/zFi1jZKqpD58QZ+wv+Yt2PCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-15T12:31:26Z"
  mac: ENC[AES256_GCM,data:y3PftGm3y8PBNzdvmA7q2aKLDcuyl9oUOYxhGBFm2nMyGxkHhpFXk6Fj1ORPimSEIO8IQaMuf4/FD6NS5nCl9oGdyrLiMEgQM5eK63CjC2W6zeVs7dMlPsLbbYa8dwth/q90b3qJsln0ffnuCkM6wjThWopaAO3jmt7/YFJDIbA=,iv:lXWb+rptn8JDHCVZVGfH1IHv07s/W8mL7QK6C1gaP18=,tag:xtl2g8o1mxoeCPAZ/sdrRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
