apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:+0i9GJbWPsJcehfU93PxoMBWQ+Ct7yRcY+aALuLubVgXXnG3x5uFrHzSWrbzhO1GvmtGgPs=,iv:C5Qdbql47++3vHlccmplvqTtC0EKhzSWwWQdCIxV/Hs=,tag:FWxmFR3682M6//TpvDNciw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMjBoOGxNckZydjZGbWJz
        T1MzS0VLRVdiQkZ2OTN4dXdCUUl1ZlJrSURnCm91NTcxQndqT1cvTUpFTkV6L1d3
        NTZhK3lyY3BOT1MxdWhnejlBaWFEUmsKLS0tIDlCb3diNE4xaVladFNoZ3Bnb0xW
        SXZnelF1bmNNSkZwQnRtbm9sZlNVNlkKpXj6212rWEbr4atD4dyEn+i5UaFbb7/f
        TIVZVueWQnPe9FOJDDXfHDCli8mDYNPdLUh/sRIo3wN5Ne6B9+wAdw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T10:52:07Z"
  mac: ENC[AES256_GCM,data:zv4PBGHutoc33psCEWsOtn/8yGR0ACfYiJfyyh3yYDPzqhTUfztSZtGDox0rJ8t/6bhgL0zoPXUf07TXh03AtZN+x7YvKah9JiOKs6bxz4+R09gcfWgIisL7E5XMgSJRIvbDODbW4wEKZDFpSQBJi/Pu16rw0/esg5r7tg0iOFg=,iv:nkOTPVdYYG1pM2Cbye4h6fj7QsrWkJiL708TYlvg9Fg=,tag:+fidaZfZ5LdrXCBE+yErBg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
