---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: anythingllm
  namespace: ai
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: anythingllm
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/ai/anythingllm/app
  postBuild:
    substitute:
      APP: anythingllm
      APP_PVC: anythingllm-data
      VOLSYNC_SCHEDULE: "10 4 * * *"
      MOVER_UID: "1000"
      MOVER_GID: "1000"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-secret
        kind: Secret
