apiVersion: v1
kind: Secret
metadata:
  name: solis-charge-secret
stringData:
  HASS_URL: ENC[AES256_GCM,data:+ZsEpvaWvGK7c1cQ2FwQi6z9318ARH6j,iv:4JN6J53GvSJzgXJ+aDkyweccQJ6aRuaHyYuf/YwyBNA=,tag:RrljAyg5HCTxElGlclPA4A==,type:str]
  HASS_TOKEN: ENC[AES256_GCM,data:ZkjWFs/W1F8MnyH4gJi8ZkAYvn6EXCGW0GreU3AFhaoDQ+s1PPFAX7XQZIBTUGM1YwZx8dbtB1+XYflsoJUC21FDCP2/u9AcHeH/D+H6OPFwKo1/JfHZC466kzvVHJFVDm/OdE98+yz1AzHGNugn2Suvy7tRTfOOz6RbDMGGY0PZRI2t/ZwBWVwSc3hO0P/YHEHu1oDZ8PByInSb9hiAeJcG2eToW56DoDhwF+3hZE5Zb5bibQds,iv:GrhTyMOM3r+OOqoi52O6/llVIvHGqqWG4ZPt6Snn+Rs=,tag:eGMpEpIO4Rzl6K9Hfv+6Dw==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR2N0QWV3ajBpZ1c1a3Ev
        Vmo5YVBQS3ZVZ2RycTFuNW13WE1aMzBJUXljCjI0OVhIQS8ycURPRy93Wld1R0t2
        WHdOVFdBcGp0ZEtZYmJyeVo3elpTODQKLS0tIFY4WWF1cDdSRG41RmZ0U3J0SUpo
        alg5NElHTmdaZjd0dFFPM21zSkFNa1EKEa/5MdDj/ABIHDgdhT/UfqBgBabO7XP4
        KzDNVcscHNULC9Cm8FINVZnn66o4tu0qkFLA9/pU9h2ebGQ5q2BhAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-15T15:50:49Z"
  mac: ENC[AES256_GCM,data:yyuVIZBhAO3rW2WigQhRZHtvg9s4COL8EuMUfohPapCtPLLDErQmKjQyaz58CjJ4GQsC+FgIl8NI2cxaHP+uTkZgOZHrtdGgsNuQhl064mPm6mfe3qs4lXp2Vl8J88XfUQ0YkKFBC7/BAmsuxvYcwv1A6VO3rgTFKd5IySaYWWk=,iv:NWSbHQWuXLQ5H0e9FKhMuFnVNReEmznpcSmhfzad2nw=,tag:ntkmiP/VydhAHbygQgLYPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
