apiVersion: v1
kind: Secret
metadata:
  name: solis-charge-secret
stringData:
  HASS_URL: ENC[AES256_GCM,data:PhQ6j6Z4BKGUsMUFNmIyT0IpmhV+3yOF,iv:Nw4Fu0mvg5iUauHEGo2wvR3WKaYCZJ5w33qexuj/3v8=,tag:ex/cUK6YNWDpenqZzZ5ciA==,type:str]
  HASS_TOKEN: ENC[AES256_GCM,data:ZkjWFs/W1F8MnyH4gJi8ZkAYvn6EXCGW0GreU3AFhaoDQ+s1PPFAX7XQZIBTUGM1YwZx8dbtB1+XYflsoJUC21FDCP2/u9AcHeH/D+H6OPFwKo1/JfHZC466kzvVHJFVDm/OdE98+yz1AzHGNugn2Suvy7tRTfOOz6RbDMGGY0PZRI2t/ZwBWVwSc3hO0P/YHEHu1oDZ8PByInSb9hiAeJcG2eToW56DoDhwF+3hZE5Zb5bibQds,iv:GrhTyMOM3r+OOqoi52O6/llVIvHGqqWG4ZPt6Snn+Rs=,tag:eGMpEpIO4Rzl6K9Hfv+6Dw==,type:str]
  SOLIS_KEY_ID: ENC[AES256_GCM,data:p1j/+1OGUgkh8OoRjOqhBclYoQ==,iv:QEV8jaL0QErilVVPp1Wq+AbbsS6fonf1cPjTMpzJs88=,tag:EQjZe8h6s4WOXFFdrI9Sgg==,type:str]
  SOLIS_KEY_SECRET: ENC[AES256_GCM,data:q5Q8U0qu15kX2sfau4qgWEyfkeUuv2CqDTVcKRmSe80=,iv:90oWbAoz62Z/X0WyLpmHXcDY8ul7m0M1FGOa0U7Jklw=,tag:JQKHwB1I7PGHcjecEg9UJw==,type:str]
  SOLIS_USERNAME: ENC[AES256_GCM,data:vGAGPm0RBtS88+WY4XkHjIsWpQ==,iv:rFeg+nD13IFGkQVlImL3Yu18LHNzRng28/EiM2uCfuw=,tag:ps988NQqz5u0vCzODGUSQw==,type:str]
  SOLIS_PASSWORD: ENC[AES256_GCM,data:Z6YCJV7l+LPyGg==,iv:rWKt5EBZObkOD5LjMi9GDzrjTqG7+yOjE8VeL0eFBEU=,tag:GD1na7AJm+b3vIzhCCrFow==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR2N0QWV3ajBpZ1c1a3Ev
        Vmo5YVBQS3ZVZ2RycTFuNW13WE1aMzBJUXljCjI0OVhIQS8ycURPRy93Wld1R0t2
        WHdOVFdBcGp0ZEtZYmJyeVo3elpTODQKLS0tIFY4WWF1cDdSRG41RmZ0U3J0SUpo
        alg5NElHTmdaZjd0dFFPM21zSkFNa1EKEa/5MdDj/ABIHDgdhT/UfqBgBabO7XP4
        KzDNVcscHNULC9Cm8FINVZnn66o4tu0qkFLA9/pU9h2ebGQ5q2BhAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-14T08:14:24Z"
  mac: ENC[AES256_GCM,data:7UCp8SsBOC1P4q1jjfCllOoIGJm+CMBpzqgpuMwPnHyAVx2WExZ8e6zmOANxE4JUPoIRoEM/hDxd7FUC++kqrieub6Y/MMf1JE9ZXDX2pBRxSQOjJxSdWDeOhVgZXasxhTAkI3twdWVa9TVbo4D+ridPXlIJGqhyTKi33/NqqCo=,iv:JYryGuw3UuVxHw4QIrWVVyPjD65wQlpULxSkmN7B3f4=,tag:1yU5yxYzzgef8Fnk48yP9w==,type:str]
  mac_only_encrypted: true
  version: 3.12.2
