apiVersion: v1
kind: Secret
metadata:
  name: firefly-iii-secret
  namespace: default
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:hsZTFeQoX6onMqs6UqLCQGQweHGp1plIcly00868pig=,iv:NrfJxf7qWDYSz79fkkrwZcGm9SRPqvcGFP2+oLVBG+M=,tag:yNGiac4wB0MhPRACmNPCgw==,type:str]
  APP_KEY: ENC[AES256_GCM,data:tR1unhUOO1vdXdGip1p3WWd+KaIsllD3NKAxdUBI+kI=,iv:8zDIHtfRoxHGKc7X8DXVTlY51WxCOFALtlr2N5is+N8=,tag:9rteoDuH/w8a1J9yc8SyEg==,type:str]
  STATIC_CRON_TOKEN: ENC[AES256_GCM,data:zcTkqM7nzQ8k5Sc6ytO8tWxLbkJpIz0P0on/Bh/CK5o=,iv:rhVYU5EFKt3p6p4ZrPr3BpyU96E0lHY9F/WnWRgRR0I=,tag:DltY8N8J8F78m7cODglk2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NlgyOFJTRHRaVUxBSGVq
        NWNJbjRrSEM5WDZwaExmc241Q1NiZUdvaHpFCml2ZGl1d3BuaUtFSDZXZFJvRXZ5
        RVZYaWplR016b0hMbEhDMXlaMG1GcU0KLS0tIEorOEd0QXRXS0ZBNTl1N3pFbE1j
        K2RlV29YWFhjL1lmeDByai9KNmRyZ3MK3BMvMXufNZ5o/WH9Nsw7oaAmno+1OQb9
        MQCpbkr+Exer/G7NGPk8LGdSbxf/sycVQBaHblag7hW1LTOv0AYNRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T15:43:02Z"
  mac: ENC[AES256_GCM,data:oTK20/TmYeRBlQ9qgUWXBX2JXulo5x0gDljiLa3lxeeLHhVIvhEIDbOzGjFN0SMl807VSywynNLqqMK1lDzDvgysp6zZIb2jfTUWip/5SOXc47hiAMIOhxjhBOkIG6yoGO8isgDDFqgT9O0ppl3ny4wHPDkgUJAfpnNddPtHXV8=,iv:kDFbbH5AEPI7O32m2MdfWY8LNs8dUck5fTzBd4qf4qk=,tag:LKZaUhPKl3sdWk0uQHE3fg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
