---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replicarr-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 256Mi
