apiVersion: v1
kind: Secret
metadata:
  name: replicarr-secret
stringData:
  SONARR_URL: ENC[AES256_GCM,data:Pg/LEw7bPJ/ayNiqhs8FNggX5B0oNT+PMWjgsu+h3GGwyKXJYRKsAXcv,iv:0TYjGvGDvEz91loSzrgBwjC6GBBEbfu9cEzp7gCxgyM=,tag:cvR94MjOOLR/u36XiMh+6A==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:znTWbC50NQGkPKZDVwx8Tyfqvd5SIiq7Eo7Jm9N8RH4=,iv:Zt9KFFgHINBJwlcO+xP60iWmJS9Jajx1YXM9nw666Ds=,tag:zogy5wvO2oc6yP9cImygQQ==,type:str]
  RADARR_URL: ENC[AES256_GCM,data:/zdkfPMh9ClAA2cUcX3fejxVL2kdy2j8cYKBkioj/eOMrdpi4+wOaloW,iv:9BaEo24Oisqdi8la7ACaMrF7TWUjJDN4jbHr1BMYaaU=,tag:2d+A6fprhlSHq2eUN2HS+w==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:N4JPTrtv/GRFOI0tdMatzoWi4E/m3lysrpOTCLchGLg=,iv:lOgKvscEU2rBkF+dLlprxicjs3Mfmz37LQeijYaJ1jw=,tag:OD4O+f2OeoVHBmXEbspb4g==,type:str]
  SONARR_LOWQ_URL: ENC[AES256_GCM,data:DCS8rEkvMjS94EyflyS7ap/0ALXjF+9HoxlRt/8K8ubmoHTulwB/4VALlTWyeck=,iv:beXf8AkLOPC+L9SVLlxFTTcXTHuwCyWAvnbPxQHxk8g=,tag:/am8pjwzd5uLh/OvGNithA==,type:str]
  SONARR_LOWQ_API_KEY: ENC[AES256_GCM,data:Ahn4ficzX88Q/x34vq1mw2AAm9bEAIIPiI/14MU9Io4=,iv:scM2h/TUVDtb+36VGCLyIdw9uzc/tdzfgwRbUtB9V8U=,tag:hTJqgdEKFtuFMSWimqzd4g==,type:str]
  RADARR_LOWQ_URL: ENC[AES256_GCM,data:BhOsxFfufOQkAiFsLNflfnULRFngux+nqhxX7zC25IbrEa0WmDpHZgK1fZ9uTf4=,iv:hNiIEwrTOxpOWpu9xXRyaBzSiz0SaeuHmO4uu9ej7IA=,tag:40E8TsiVDy9goekC58N/Sg==,type:str]
  RADARR_LOWQ_API_KEY: ENC[AES256_GCM,data:RVm2P7/j+evfCrk/uUE52tMjbcCIWYFKVYyMebj49qA=,iv:i4cp/X0rn8UxY3r48+++CDqYfp0dnWB1yltMDMa4tkY=,tag:6hsAcCiK5nuLcDW2SL7MEQ==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:hKIi7bcWeRQxmPztvuv/NcBRbvglpDVcxS9C1imiYIBE53femVTDLZlZWkg=,iv:In0RkTLEeK7DQn1dl+Ggi0EED43oG/JRC4jRzYHVxfs=,tag:7A18WxrOmKoNmcaej9H33Q==,type:str]
  NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:PUEROlehAn6LdgEIF9WSDuNBR5v5g6xJsRE=,iv:DQvAv5NQF7X0JjdqBr8qcChTuNJDutQ1b+vLmm1kE+Q=,tag:/upWQZ/HIOBwoAi5RCSqrA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:pG7Gh0fod//49aIRxS5HN0ov00iC7VTtiBtp,iv:R5r6GU8lEQoccuNiI3r+Ipxa8Mjdahb8B0h0753bl/E=,tag:nUL/zWVQhgctI0T/BZ5vJA==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:FPQaZgiOfuTLnA==,iv:8LWUS6oqfrs0CGXkp4bXVpM2kHawi94kfPYjMT8TEKA=,tag:QCiCOItcrSxAemu2PVvBtQ==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTUxYRWJLRVR2OHBXTDlC
        STV6QzhiYk1RSXdudTVnWjJWMmd0SXdhdjA0CmVMV0ZENHdwUEgwZjRHTVc5OW5U
        QlZwbWxEZXlRYkswSURoZlR5WkpmKzgKLS0tIGc5bFY2aHFxc05IQkF5Rm9zSGtk
        bnpocDhsNmxzOWhZQ2hOQzBxb00wZEEKEO1yTvxVnyDyjKxwDbFbYGi5CqFpKm7u
        XBLBk3K2bxdq6IiPUy5cHwOAb9mZDZLLyw8fnHFO6KcwqmzQgUrxQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T23:04:37Z"
  mac: ENC[AES256_GCM,data:zNKDNg+6+eEnUFjT9QeAeJ+IRVg/+V9pacA0QmgvYsER3nn4hnNiekhDwYe2qcwLTTu/pxX9ibOqSxNhsFV27lK63fzelaUaBpeApc1HSKOjHSYlcEhSpOLApqCL0owFsGTrc8JIF8n3pPE/EP6H7qWYqe8mHDV1JKnDZ/4Ku4I=,iv:EWSheayYjqmz9xsr3SqWEZ+0rYgaoVpXI3sejtbdZ0E=,tag:Q6TFXI1Za2e7CrIV74FVaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
