apiVersion: v1
kind: Secret
metadata:
  name: replicarr-secret
stringData:
  SONARR_URL: ENC[AES256_GCM,data:K+/fzB5WR6OEyFyCajtxVp1wxFkyI5PsdNyBIPNriMlW37iqKaCXl3fx,iv:0Gs18ceuoqKHr+hZN3TFOFPdcmcR/8W/Y9cHE/rGLGA=,tag:7P3NYDel+IB3iOFokXuSjg==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:pwwlaJNs/ZZuN6hQC9a2QKiFq/XJJeAWk3lg2cA778Q=,iv:xZdnFmpYTLTKN70b6O8tAyaCHbC//ad4VwZIWzwGN18=,tag:nFeqcFYzPE2flG8CAe/vZQ==,type:str]
  RADARR_URL: ENC[AES256_GCM,data:sHJRm9I5tvm1y49Sk/hw7PD5PSnaRkJEycQIvcJNTZr3a752xSKbH9mR,iv:g5XpPt4weBTJWLZGpfCM063ym45lgnHmBYxlfem47zA=,tag:yoG0wJB6QVBuJmzW2X3ypA==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:RtvYUmtjABOMt/JjR6uhtUlnXSEQOH/JW6Gkd3SBDlM=,iv:lIXQcOr9WxOMyajZxPrIalSgZ7zZOxwjlsi7m7oXjCk=,tag:x2Jr9U0Ox6v0HGhkWjZXZg==,type:str]
  SONARR_LOWQ_URL: ENC[AES256_GCM,data:2mSR4Vxoy9b3bgt/vyIpajZn2s6lYBbJ1lzkWN36nNyoPnWktM5MlD09cMNXMXk=,iv:Kb8cpaFTFLb8O3Dt2JRbA4vP5PnEV81giW7y32xhOaE=,tag:wwXcE4eqd2RqT+J4PYKgNQ==,type:str]
  SONARR_LOWQ_API_KEY: ENC[AES256_GCM,data:Wp2uz9DL4HxripGEG/6okjy8Dh64hV11BTzcyQ91hZY=,iv:DePAsBzA3US1FL8GQmtRqJ66PHG2D9ypsLIx8QJuhnM=,tag:0uojC0rRIozNeAj6UDYeJQ==,type:str]
  RADARR_LOWQ_URL: ENC[AES256_GCM,data:G1A0i3jOTYjNZ5mKYmveaQSG9RUsr68qxVdojBZ9gZ2QpbdGTC6jKweq1uhDSJQ=,iv:pB2ftR8qi8u6q+5R/cBmzhvIY5FjIlYlJ7siIvFtJO8=,tag:YNJsuE0lsPHtPRmMljM8CQ==,type:str]
  RADARR_LOWQ_API_KEY: ENC[AES256_GCM,data:uOqkdjPlAqJicOIKDO3MdXKW73VpaLI5i7vYPF3cCKY=,iv:1mqhlAwHjzzFgVhk4eFV5buL3okWOWQ6xHSFUGQ1McM=,tag:dqK3mO7RvSr8zUX4155GRQ==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:kgsn5kZN0W/X6pcY4o5xjWf44nXsGR006dgjAWtLAk427rQCxaqqprAx6xw=,iv:WzOhd/zBc2L88eIfNM1fj8lqOpMAMreXLQeGH7zE+Hg=,tag:UQ3Sq/O2CGrMtd3EVBlc5Q==,type:str]
  NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:GUZEJq6BMbMLYde/W0cOWNKaQiwgB+A7mHU=,iv:7P6vj1FJPImlgLp2ZjHLQghEIW1/CoRSLdCZky6hSXE=,tag:mGOnUpRicKz0HUpDioMBWw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:FSPaJGjypTwa7znmPUvVmvWntQigt+/kjWCY,iv:uPZGjUXe1husazSaZnq/SvWBWR/BbHmByYKLF1B9++o=,tag:7C4uH4TFwTGRN96cPo8Taw==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:FHiTmobnfsesLw==,iv:pv2qopcf4PDCBeg307WW2oxT9Jb2zuiIx4FNq9tUaGs=,tag:wtBjxzQZC3HdxDHDdKu0rw==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWmw4bUZoRXg1SGZkY01P
        bDI0SlFKVUNTWUNUaW5ReWJ1Q2lMUUNyOENzCk1rMnhkSmkwdHd6aFc2cDhIZWht
        YVY1VXNZUXF3ZlM5TmQrZE8wK1FGY0EKLS0tIEY3SXZZZCtDTlJpMzI1a0YwOHRU
        RWNadi9teEdqRTh2a1Q1QnEzVloyQmcKKs3X0IXPig/C5k6u4wt+jjeLvUGrKQ0i
        IPITlZWBvEblhd99kdrNQ61Gom3TQlHd2dk++YMWCAYdFck+gOeSxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T14:34:23Z"
  mac: ENC[AES256_GCM,data:ThtdlZtRAuX33ymo4GUrlLbmONnNnzSHAb7fvt9L3vLxIDr97RRbyYTQ7+ZAhS97elT/vIPM0lVcVVvQxHibHYeeb3um95JFVHAzyKzzQj1q2v2HRRTPGXPYX0h7m0moL46UjbuMv0bh4+yN/GoV39FbcsfZNNKHegc+hS0KmD4=,iv:YeAu0scEMl0FEXfF+jvCXO9uOFt9lrhVyLFJDz2qDV4=,tag:GibTLPWmu+Cc7DlWhOgmsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
