apiVersion: v1
kind: Secret
metadata:
  name: replicarr-secret
stringData:
  SONARR_URL: ENC[AES256_GCM,data:Q8H7rfvs6tCnD3vIRVBb7SD323zcOtRQSIF+rpvHDd6mBsIZDqjnZMcN,iv:L/K+iFJ5OqJPAykEtfPMtjTHHAebhnzhVR04fpFQ4oA=,tag:qRdI2XPnGn7LGRlIafJhIQ==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:xGTZQCBq+jnZugV62rmaHQJB5qxrYPE2VsKojg/E2uU=,iv:luN362FcrucAx6TsJtAt2k6RQrSLbDmS3UNhDFriSY8=,tag:NEg9fS+ZztZY1ybyRK6Zqg==,type:str]
  RADARR_URL: ENC[AES256_GCM,data:imFa3H4I3Wo9fD1A2P1fWQXaD1mRpf4whU899iqvd1hMp46UIH3GXLpJ,iv:nht7biRm9MFUhckUQOtb/m8bHlrku9dHINmC3n8Bvmw=,tag:eEwUykWKYVG7pSQgPDWvLg==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:pQ/7HCga1MPL7ml/MhL6F9C8za4SgdoI3fx4GxRnmIQ=,iv:hUlyOSMYv+cf5OCqrfJS7BzR6DSlZnxTtxxZyNqtlYg=,tag:KAoPZPJv3vAyM6Oyyr7aGA==,type:str]
  SONARR_LOWQ_URL: ENC[AES256_GCM,data:sXGohPTXIfG36Vcsz0Ha5sCIrBTdvuFZqbSYqLOpv23Yejedl8KpDein9Pcn/Cs=,iv:9ugnhO1aBNwZ1FZzqBuwPDuKODCGSgaqIeNWZyTeWuM=,tag:UmaVrTzi/NzYsGvDddIr9w==,type:str]
  SONARR_LOWQ_API_KEY: ENC[AES256_GCM,data:2yrWvTLZmi2pjMNsXO1VAbF7ui0gFQrestp2xTQIumw=,iv:v2TLBFHEz+O32cNjKgXkl5SjEqJW8bZ89SmQCnc7+oE=,tag:4TX6NlNxgAPV71RaBaY5Ew==,type:str]
  RADARR_LOWQ_URL: ENC[AES256_GCM,data:N81x2ULHUyS4C/QF0zhA4Pu3nPAjWTRBmsMEtQKJ/wD2niHCnLPZYUFzwOdH8tY=,iv:LbM3h7y60JyJjxhcGApwQxKdS4TD82fFKd7nLwfnLd8=,tag:lpArza7+1SuaEaPngj55kA==,type:str]
  RADARR_LOWQ_API_KEY: ENC[AES256_GCM,data:m0PxRty4VmsaMA1+Uc6wKl6XtgDo/gM61YZQfA2HMP0=,iv:Vh5SxalZ62kgJ/Xa64bi2JA6wI1f7DWVEw/TibuSX/U=,tag:drKxZK+P0xDiDcV52JRSZg==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:MUjVx4zCYHm2smNSiWrvDJYh5eevSUgEI9uevU9gPOjIiH3WX8mPEmEQQH0=,iv:An1m+qdf9Cuv3+3bRuoCvlxnrnKbHq3svlB8NVYtOTI=,tag:R4ird1TPI3fHMwMZ+KDiig==,type:str]
  NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:SSscBNDSQuPwL6UqJZLrzya8KWmotfMNDug=,iv:HWPmtXTWp/xSNdMBtuOQ8GqeXy+Dh6MXeQBFfipRJis=,tag:fNPSD9CjViT7EBb6+0zknQ==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:GiwWq49Qy8FGRA==,iv:ZvsbR4yLDfg+Tdi7yshZdpCuMdzz0r/R28jiBSUUy30=,tag:Gqf41PzHZVEBEs7MZnQgNQ==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOG80Q3Vta20yNGVuMnNF
        SGdaM1FHU3ZLMVB0NWZqU2lvWnFKTUprSFNZCjE4Y3JHQmV1UUwvRS9HNVBVOEI1
        NkJDbHZXN0ZIWmdYdS9SVUdEYzl5NlkKLS0tIElzZmdJNUsvempnQXppRzAyODRR
        SW9OaEpDVFIrK1R1RGc1NWFaRG5UakUKzamkydfT7GxGbVjO6eBL+TFxHFTmY+JJ
        FxhANksnkCwyCTkj4M0r//rmYqdw16QVlQMxsyRC2WeQYtEHvmxEgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T22:46:32Z"
  mac: ENC[AES256_GCM,data:dxy+UseOgQG6gAx+xNGFTi7U9k8LqyyphRPjaeoVWfDR/nGVYGoysFJQs84ADcS8fytoWAUX0z8U5Nlg5YLiECYBWKs/gu16IXfSv01o3hSisgx7X7r4UtyReSPDSUeyleoJSv/M8U8N3JMhoG08rgYn2JRdIGzoQ+HrzMSno0Q=,iv:aGIcBqZnqb5xs4q7JEqx/bQ9Kb1UucVfrFl+zWDN5WA=,tag:EZmd3ugpTnoC+XZvnhBAyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
