---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: syncthing-external
  labels:
    app: syncthing-external
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["syncthing-mac", "syncthing-arch"]
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
