apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  PUID: ENC[AES256_GCM,data:29726g==,iv:oPta9DapxiGkls+Wxd7Y9w8R5/AmAzQRSI394a4QCvk=,tag:ceed60FEU7RQgH7Kv1y6EA==,type:str]
  PGID: ENC[AES256_GCM,data:7oOYzw==,iv:58k/ZQFx6c5sRLfasoCAzTm/YSTZmFMRE1h9bOBJauI=,tag:dThogHgmGo4KqxEUJlPjZQ==,type:str]
  TZ: ENC[AES256_GCM,data:/wWQi31Qk1iHD3Ucmg==,iv:gkN8OD/3GGcpeQ/u8mMLEzAxSHU9KxuzGTEWa7kAuIo=,tag:z9qW8UAL+n4PYiJSiEmyQw==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:z00b3/tZL+Lj2LiJDSTSQBNUKSopJg0faoQIDJ8cG4Q=,iv:m4MnTc2KfDLkIG17y+P4EBEc9ZlgoxAhfAyjpt1FrNY=,tag:I5UoL9tPvChCzWHeTsY14w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U1lzVEZjdVpDZ0dCQjZJ
        QUt3ZTJjZlY4aVhSbnZrR2xXYnJZZnBXalU4CkRKOVpYb3MzL0hkQSs4Y2czTWxh
        VnNtd0RwQVVWOXlvT2hxYlFhNkNLdU0KLS0tIGZ5UGltS3FYOWdNYkVnTFo2ak5M
        NzlNbWo2NGJ4YW5WV0VCMDlyZ0IycWsKutKq3BezW+XEonD7uAsit1x/0qYO64D3
        V5iBL2qjH7dcHKrAx4v4ibzjuOzrllPMUv6Ragt6HJeD6qMhEuN37Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-19T18:57:37Z"
  mac: ENC[AES256_GCM,data:mPBcPHtTnIvjgoRss6SbhjtHF5pziij4fBQY7jW86ax8oGStJGDmd5IjKzAc/aTfSBuLeAJtRp/q+CIuEXaIj4Kj0CFZiNuoIPKLV7mmXc/Ut5EITQeT4HgxobVLobzJKrD1Q6jbKHxkosxy1M+XcPTHP/AWaVtvy1ZnLfBjBBM=,iv:hg2oD3KDgs8CKLYeGWRFK8V34b/6vaHs37EmHaqSQMM=,tag:hr0BIJ0JTEc2ePylaOe6Yw==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
