apiVersion: v1
kind: Secret
metadata:
  name: alpha-secret
  namespace: code
type: Opaque
stringData:
  #ENC[AES256_GCM,data:4JCiJYmx2dMnznvUPyFpS8kqPllEIThQZNh0IuitKA8jtnvETqBnw//vaTdUUT9EC1NxZzHBlJ4vQ4IHSV4zM7SudA==,iv:mmz3aeSGFT+JADYxzTbTgz8nnN4f29ccsV3p3mvAZKs=,tag:pShLgyFkQVITmU7WpZ9aXg==,type:comment]
  T3_SETUP_KEY: ENC[AES256_GCM,data:tGb3wGjlUfIVmWnX/C36am/3eA1kki6iB9SQW4ST2kvvgjxTA7OiMD1QlyTOaMbe,iv:BlcRteo4z6OT20dUuXf5oPvwSeM247t1ekKG67YkzHo=,tag:pY+JuiwJoUe/fywhk8Okgg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdWVnMk12cTVYWTNBOGtX
        NHRiSWtNZWdBVEJJeU95bUFydjBDNll1SWlvCm5ZbTJOUDFZY3J6ZmQ3QmtXQlcv
        R0JHT0tqeXVIaXllWlpHalJ1YXdjMzgKLS0tIHF4dGJjM2hCclZ6eDVFbk4xOWlV
        YUVHNmUxL1R4S000UGNwVkZuWUIzQjAKnngCErYH11kWb/TZ4sKuNGUCLbjIdprV
        YLV0Cyqe5Z4iZFBhkfJI03lTwtJp0AY+BGwH6UUGhtPb3Xy8d5lJJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T16:29:11Z"
  mac: ENC[AES256_GCM,data:fBbTltQNxRL++VAAWzN+rzZ1ByS4uGIOZ++RPm9Mnvs5n9eEj21PUhJ7QPwWatBI9o5SWlNLrDR3mdoxdORmWazUqz5fT+uaVg/A8tcQNrgoRh7CVlogCn4isJ41hZ5B3nZV1rJX3h1FI8jk+ez9PoBMoMpCHIVydROXAqwJCeI=,iv:ng59VOdVPI+OudRgaKvZUIXt2bChTU1XYhJIhtdqTSk=,tag:RIXtrc48D+WO+Vv4e7+xdQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
