---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: slate
spec:
  chartRef:
    kind: OCIRepository
    name: slate
  interval: 1h
  values:
    controllers:
      slate:
        strategy: Recreate
        containers:
          app:
            image:
              repository: git.iacob.co.uk/andrei/slate
              tag: latest
            env:
              TZ: Europe/London
              NODE_ENV: production
              DATA_DIR: /data
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 10
                  periodSeconds: 15
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                cpu: 1000m
                memory: 512Mi

    defaultPodOptions:
      imagePullSecrets:
        - name: git-iacob-pull-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        ports:
          http:
            port: *port

    route:
      internal:
        hostnames: ["slate.iacob.uk"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        size: 5Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /data
