---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
data:
  config.yaml: |
    server_url: https://headscale.iacob.uk
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    private_key_path: /data/private.key
    noise:
      private_key_path: /data/noise_private.key
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
    database:
      type: sqlite
      sqlite:
        path: /data/db.sqlite
    dns:
      base_domain: headscale.iacob.uk
      magic_dns: true
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8
    log:
      level: info
