apiVersion: v1
kind: Secret
metadata:
  name: cliproxy-secret
stringData:
  config.yaml: ENC[AES256_GCM,data:TFsMTvzRd8l5H63QdTxCtgKF+Zg0ZrqgmU9i8dAqSolUxQ2fKf8MDMxcU1+9BQN5fy5uxjkZPnVZFcq7O8vVqQnpcMFzK6y/nixzGxFXwQm56sSxrgMe1Jvo9YtUV6hDMIK+TEF+PqgV0kxa7gmGeoHvzTHKkWI3KCFxw8KBdP2XkRXMhd/TbgLTFOYH0L/YpRz24+Jghoj72uXjjHP7xZslkJg3x29KxjQiYm5zlVf8q3ORJqXeOKvRV2Y5QI58BtW5inxETL+Ty72Srhefd1uok5406fQ3znu5UO8DMhlm/S02ADKaP9l6JuIlK2n1LEunhmi1a3iBNbujFxVNbfcgr7SrTH7u5SCSa+O/+uplne/2hZvZWFb3qIM+J8+ILwXRrJ8TfYK/SvTcAN5B4mStJPoFQBIZBfFBfImnv76wkd0Bkhf835OhFE/BqZ6Foyl+t30XB1gglPA2Me73oaEa3sbKkx2szLN6zg==,iv:/7/tHaalP3El6WC6lLACbjADM+bnW/eJ9MNHHmPYZoM=,tag:5t3FN5F4caSA2/JBYpzGpA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMHNHcnF6ajRtZlBvV2ZI
        TDhwUytPM0k1R1NJTDF5K20rSGNweXV1bUU0CmxRa1U2eHNnNWw3eHNSeG1WUkl2
        dDl0cGtnSDdaaE83Vk0rbUNKbldhR2sKLS0tIDIwdkRPb1ZQNXd6Sy83d2IrYXhi
        ZCt3dkw0aVlDQ25VQyttWTIyVTdYaU0KLqp2LVkGN8nlUKIaTXp/l4chJqRrl2fe
        hPL95vdLGVjHrCVJ/M2MMJ9KxeT4qgSI5kZ2HqjacgK2m0KNKBqotQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-23T15:39:45Z"
  mac: ENC[AES256_GCM,data:7Z5hzVfEdoLtmW8kpzWcBBrSZ8UmcM6MA2AW3cS3tEdYOi2XI+Muu4ik2/sILb4c9agSk14wKEDz53O3R4JvGYl3oa5WsOAyiFfdBRpfAZkZxw+zXvRAAQrV8ukHDIhOoPyV9rPqdblAXvuXPB2XJkCt8qUgoFa9hamQgqc+QvI=,iv:uMnuOOw/2N4tfzPcZObFK2FH2MeHmDZJgw8BhHwdkLw=,tag:ytYQABzfYzwgU2QIrpN1kw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
