apiVersion: v1
kind: Secret
metadata:
  name: readarr-secret
stringData:
  PUID: ENC[AES256_GCM,data:qMdF,iv:3WgWC2sc+rxq7uGvjfQpJeQctnkOQ3Xqwb2SNSvA2MI=,tag:NithOrxyM8XE8CWEuz8dJA==,type:str]
  PGID: ENC[AES256_GCM,data:fErh,iv:oQhXkAwPgQ/vdTzdtHYDazf/+Fl5UO5OQkbsu/N3n2U=,tag:NfGHanCLI7j9VZaj+Cn0Sg==,type:str]
  TZ: ENC[AES256_GCM,data:dGiNJPSOP3rEaCnl7g==,iv:AFRfXsNWAC87PXsirAESrLJmiHasZ67tuQ2aP4iRFbo=,tag:lc5uEQa4KqNIe8xKHbtjHQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MDVMUHN4Q1NzNzIrMVFF
        MlloSlc3Nm1zTmRlQllaQ1RvWDhuNHlnMGprCnV6a2o4TTlOMENieGJYYTdZdFNo
        dUpDbTNOS2dMelBzWFJvdi9JSldpOWcKLS0tIEc4ZC9TRzJsV29BUmRmTkpmeVFt
        ZlJlaktNazBxSW50Z3FnU0p1WDY3aWsKJmqyeqaEqfO60UUQ62fRssijB+Kp2OhL
        g3xkJd65A8becON6xLFFXSI6MBkfi9JmvqfX7M+t4TvZg0Z1J6aoqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-11T17:28:41Z"
  mac: ENC[AES256_GCM,data:OLHhg9hn28SwAh/aPVDtDHEsbjPKEwWLdu1aLYZkDz47RMgMGthaWQA7/nXpDfXHG46Fwo32uqpYI8GpSVoSw3q5SmTM2VmgNyPK3/yLSSYJkSbxJxdAreDBHEaSAds5MJu4DtjqRGO8QW0vB1QoIBuub3oe7rJIqw7L8ytYGfM=,iv:weThEDPaWvbJMsF8Xew3kYI4D56h37KSSGiFDrONIQo=,tag:YM6aXZJj/6uC3YwrT6ex2w==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
