apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-hermes-webhook
stringData:
  token: ENC[AES256_GCM,data:H7UpOVA6Z2gU4nJeEixkuPTvZ/bPEJ3Xkk8IlTZXGZ0ox1d0w9tILrkxZQ==,iv:Fs2+JhBFPSYN5NCnTo/YUt6n0FVab0ohPs4Z1MXQ7xw=,tag:EJjI/DR85KDd9sS82jHUiQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV1BWRzR0ckZWUGtxcmoy
        WmNualFTdFhsSGZzaVJ5YUtYOWNLZ3p2N2drCmhFT1JUV3UyUys5UFluNXE3OUx3
        aUljUFpNTEY4VDFGNm9hSE13WE9LRUkKLS0tIGc1VWM1UUx3UkdhZFZJdFcxR0w2
        bUtIUUZsQWxkaHZ6ZmhtdHNQSWY1OVEKtfISD961LHcyu6xXzPZETDf/mNRLUeS1
        cpNIWdeHZz07sB4Vfs4yO/iSJ3+ANAKugTloCtEaK3z6Q1VyRM3mgA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T03:49:02Z"
  mac: ENC[AES256_GCM,data:j+Xyvolilp0DLpUmb1M5g7MWabHMmJ5T7SNgHvTxNJUJ+S8bP1jOHA0DpYsItNgRsHGxVK2bt9wDkcBUecKHwmB/KoddP/3xNJWJnbU1BK+IvQIV1TKauGqKnHeitWEQCP6384TgAHhFFa3zUKo4XnLIakDckOdGM1f8roDez2g=,iv:OnfU7MwfKc4Kat4MTqZznyPvIcf4smjjM1Z+fytWLp0=,tag:yIbRdlr1qkZ2YVzwvAWDww==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
