apiVersion: v1
kind: Secret
metadata:
  name: unifi-secret
type: Opaque
stringData:
  MONGO_PASS: ENC[AES256_GCM,data:dRYCvRBk/iyov6eY2j3zRENV0+cHe9ck,iv:jq6KWlYKTLY+fpBPfwDEkD8EciU2xPUQ6hyvgIIWIms=,tag:HWHtlS6C+93tbTynUymgNg==,type:str]
  MONGO_ROOT_PASS: ENC[AES256_GCM,data:TX50x9hICo5n7nSCkqzhV0bq6hMdQFph,iv:A7ob5RbU7oVErcLwtjk7Amj1gdsv4eS+LXqwN12w8DA=,tag:grVWEpnJujpZIWfejiSrgw==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SHVHK2p2eHp2K1pQMW5s
        L1BzWmJJUXdWdm8raEh3RTJDMU9EcWw5eUVNCjQ1dzkrL0pLU2ZiajJ3TTlpYlAx
        VjVYNDQvbDRhUDJPSjZjb1IxWjRGRG8KLS0tIEpPTTZYVS9VTEJoWG9wSDJ3UDJW
        enBmVk9jUnhweVh2WTN3cGF6aFFxRUUK3SvIIsmREi+E02nrpdAku7s+QWr1SeYZ
        hc2wcDrmBdv6D4FekyNd3aelE4KCHxx36k192vg6tq/mEsQkQIJ1yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T09:51:30Z"
  mac: ENC[AES256_GCM,data:HUvKFPWswB5zqRjJ7HuSjFcUkrQ06n3SsSwNZPt21cziVcyhisAOJlU4opUBzoBRfPwQtEA/0ukPk+Vp5xjpuGoGHGN9LgrX8r/AnecH5X8icxgOrq6/NYWR/RcOk3dyO9LWuqwGHGhV/PuOUt9JiqDbfokndJ0vzUxDAlCgmK8=,iv:v6zsf6zK3YT0xJIGHdf/RdK0gRRtHCUANI4UPE4HkOg=,tag:KbIKzzeQn8x31ZwVgimUgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
