---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ersatztv
spec:
  chartRef:
    kind: OCIRepository
    name: ersatztv
  interval: 1h
  values:
    controllers:
      ersatztv:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: jasongdove/ersatztv
              tag: latest
            env:
              TZ: Europe/London
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8409
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1000, 10000]
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: openebs-hostpath
        size: 5Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /root/.local/share/ersatztv
      media:
        type: persistentVolumeClaim
        existingClaim: ersatztv-media
        globalMounts:
          - path: /media
            readOnly: true
    route:
      app:
        hostnames: ["ersatztv.iacob.uk"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
