apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secret
stringData:
  PUID: ENC[AES256_GCM,data:bZ1QGw==,iv:OAkHSIJiqnzPrEs4z9CdT+5WWMaC8Wo750cnOHWaR6Q=,tag:8KY0tAcruR5T6TX1R+xYMQ==,type:str]
  PGID: ENC[AES256_GCM,data:fFuaIA==,iv:F2+3+N/+t7+wa0BrPBnC9lNZV8GVIMYZswVWjH82KPQ=,tag:8X7P4DbGu4puS7C3pZ2ttQ==,type:str]
  GITEA_DB_PASSWORD: ENC[AES256_GCM,data:YdolF2wIxb1LfrB4/wKCw6KjN4UcJyoFptVLP7+9XArc0MRkQHy1bIVaFbF14HWrO/q/9+VjQWRLg1Lew/lJPA==,iv:xY3/Nhz5aaMRpyCG/UVzNNVJGHynv4mWysdpOaLSqPc=,tag:kbAhFOajcFu5lOKCVtPOMg==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:3sBLu7BQhSBZXdXc/ovPnR00Xsgqnq8rHXz2gBPCKnbrfgW+Nk6XQw==,iv:yi3jMnFFzGZK1vzTaRT57mhes8sh0a5Lewka2kogo1o=,tag:aOD14+mSHxRUrqt9R+yZmQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYby9lc2xkdzhMRTNKTXlG
        MnNFRU1kTjhYUXVVOWVRQ0xoUFJJTmJJZVZFClFUNWtpSnE5WmtQMjJRM3Q0Vlcx
        WTNMNVpVM1lmMHJybjg1UldXK256dTQKLS0tIEd3QUhTMnRTWWZKZlZ6NTd6ZHox
        dWEwNnlGMVB5b2NFVy9rczdPMG10Y0EKPCibVVr+EqRYVS8y1Cj17KR771NAIszM
        mgFGEfcnzyJg01tJtiRHqMbVdpsSGBDrrV9RlOnZdI9tWlXgiY1PeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-24T10:03:57Z"
  mac: ENC[AES256_GCM,data:yyWMvGPMBIY5cI7aPP33WwlZBGK3h0YHa6UkriRNyP5aukUkDxIGmokfJgk5hgfNfa8ffmFl4tzEJUCKucKKO50AJ1UQ4pA5Hl39GKT4B8dM/5YqfxfiNrXBcdPv7Dgma3nnp3CfTaAAe6newma+uKHHTOxQzhvdLQUttfIGJwg=,iv:zSX7dluzpYhYYVGpkGmmwx/m1GNF4qitMKCMocQE/0w=,tag:yu3Cw0UquYTyTnjFQs+TCg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
