---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pgadmin
spec:
  interval: 1h
  path: ./kubernetes/apps/databases/pgadmin/app
  postBuild:
    substitute:
      APP: pgadmin
      APP_PVC: pgadmin
      VOLSYNC_SCHEDULE: "15 2 * * *"
      MOVER_UID: "0"
      MOVER_GID: "0"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: volsync-secret
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: databases
  wait: false
