---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-recordings-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.67
    path: /mnt/sexy-pool/frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-recordings
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: frigate-recordings-pv
  resources:
    requests:
      storage: 500Gi
