apiVersion: v1
kind: Secret
metadata:
  name: truenas-secret
stringData:
  TRUENAS_HOST: ENC[AES256_GCM,data:We9NHwRDUFLdl9Vm,iv:z0w+twggYcGuI4VyAwe8kQn7M8AMutgdnkDoK41ZrAM=,tag:GddfKgpVHHLuTlnBWypSkg==,type:str]
  TRUENAS_API_KEY: ENC[AES256_GCM,data:tfN5XplhZ9dEfkD3qQi/jc9d2r8WRvgZTd2o/rDEQYisGY8DmBwcA84JCKjHkvBeXXeMQfdwkGdAxnGzvJnrL7JY,iv:Wpr0a4U5PJ+G+KgjT+hjaijJVlHEDnpjbjk9Wl+tqOI=,tag:h+1lhLgRTd6UJtD/DIiAUw==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc1lNRDV0WjhPZVNEN0VM
        VFJ4TFVMcTNCQUphOGhDWGJ6cHV2cysxOENrCmkySFBCaG1SdlVyOUFiNTdOeEJv
        TFFYdG1ISlZEalNsRWdZREcyS1lOd3MKLS0tIHJiMWQ5KzM2RVhsSjVHSmJpTEV1
        OVpDalhPa01hVHdsUHpvY1JrNEQ3VUkKDNsv5aOOSbYvjJuyAcJGWhmEep+++PkO
        J+3TS8VLsf3efbJ/hN+H5rH2seniDGOI0noBJYBufrVzK6SqqDhgJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T22:43:18Z"
  mac: ENC[AES256_GCM,data:N0GGQGj07NFjNfmC4ls9MMkTvTRgfLoe6MkrZs7hyjfE+K1BYYClLYyrwp4hevmvk9bWJtLuaozznXINb9fBryY3JFL8xiqaczVonI+8VLUr/sLFbeiDbbw21DYIqr5tvwpZjo5bymI7nlxJ0ZIOmiu55yP6U+4stBw7wtsbPxo=,iv:vcEp7T6cuoYMAtphDEzwdw1g63ZALFV43+Bn7WhcY38=,tag:xPbkTiBJzqFjrR6jdSi2uw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
