apiVersion: v1
kind: Secret
metadata:
  name: plexo-secret
stringData:
  PLEX_URL: ENC[AES256_GCM,data:xkRdMuHX5cPFpt1s5Oh1AHL1qJHoIakjhdRcepYJFmJqwK94rxJ1gPs=,iv:zC1a6yUB7M8raLnQ0PKQTKU/3NTVGK6o3pmJGxebnW0=,tag:ZJFeCpNK3IvYMepAaKFVCA==,type:str]
  PLEX_TOKEN: ENC[AES256_GCM,data:4JrbvzBkmDelkqalQawBEcBBtrA=,iv:ANlSlpA01IqjmtFYXHQxHiVlVtYNyGzaNs9hYMKBE38=,tag:hHvS/p0/bZ8K3LRgDhoy7A==,type:str]
  TAUTULLI_URL: ENC[AES256_GCM,data:NVBEoDaXOoXW12D+Rv+FeJsPX8b2T7ExNZcOF/1uLS8cBHtL0MrIyHpM,iv:0yWJQPtdAjOTq26muNqfAiK5qAUMMUDu2n0U5Xra2MM=,tag:0Mjks4VikdnlMLMmWMREiQ==,type:str]
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:rsUde7VNRb0Z1Y5Ou8vXbFBJjsVIQmyICBemQnIU1/s=,iv:ksX/w6sVVdiF+IJhdNC3w3Teqmq72KwJGQH9DQTc8HY=,tag:h0yo5vL+CWRpW3PgxcKuJQ==,type:str]
  REFRESH_SECRET: ENC[AES256_GCM,data:rkdg4DcPY7AFbTP+HDRrOyTBvOAHAogj,iv:XAnJ3rqLhh7LVPssNEbc8y7ogIaDKBSbg//Uv2hPEm8=,tag:PZwZLfkPKcWY3Qdim4t5UA==,type:str]
  APP_URL: ENC[AES256_GCM,data:Gl2fEquuiuGHxUzq77Vp51kOoZxQUkmMWQ==,iv:e38DEC7xo6N4vhYmGvx+Kjte4vMKPVuU2CfGyYuC61o=,tag:No3L6SAW/XdG7yMsFgl2UQ==,type:str]
  DISPLAY_NAME: ENC[AES256_GCM,data:h9Krdsab,iv:2b/SeOa24+JTGbaUVOybdr4JJ5YSa+JnZI7luMKiZEg=,tag:PdCYkIUEpF2wq8vv+hXHOQ==,type:str]
  SHOW_DEVICES: ENC[AES256_GCM,data:P+vBOg==,iv:P83SpAv9P3tku5oHoBxkdUwt+yTOHsDhErb6jtGgt5Y=,tag:oF9hKXF3PzFqnqnRxr+sgw==,type:str]
  SHOW_LOCATIONS: ENC[AES256_GCM,data:rVLDxg==,iv:T85LbGSDtcdZg4lX+Zn02FwudBELy1VBDELJBSVBCdg=,tag:SJ0GJWBaWIz/7u6sup7eEw==,type:str]
  RECOMMEND_ENABLED: ENC[AES256_GCM,data:1750PjY=,iv:h0g417BZ+MUuI3KcVKChoGuIpPTMkbglo14hLI+1oe8=,tag:fvpYpr6gokhzTkBDgVdr4A==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSlhvYlhBQ28yR2tGNEFY
        MjZjTE02ZW9xRXJ3d201L2c0Q0RMcDRoNHpFClk4aDE1emlaWngzZDYzaG1yRVpC
        VFhsMnorZHZaYmJ0MENrNEEwTjljNUEKLS0tIGpvdGc5am1TckNDM0hXakx3RU80
        RkFGUXRUT21ONmh6Nk0wd1dyQU9VV0UKbyKkvQ8E3BVcmgvkg24eHNk3Fs2FlmsN
        q+ic5bXIaA4BXe+JoxogQaMM5MrEHSDvKqmi+feYPQjdBcn12EwmXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T18:29:35Z"
  mac: ENC[AES256_GCM,data:ZIWLd5DwvVn8/fdYEwbdNCfpXFe5425e/3xGNXSRHIvXoJsXfKbP71AEoeZsuJcQDe4YM3OUp+jszy7nQc0gxkBKYbuchf6wy2iAPvRbuuyaHHgZNsIStS+h7fG9r7kxiCF5OiM8hIQHgQnskEFv/51GfhsKU8nKcz2A4UYSb9g=,iv:kiq+Uraro6xB+hSkvtYvQkSi2K2jEhe5VDdu5Br9x4A=,tag:V3PKbiylM88FUfdPqSBCBg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
