apiVersion: v1
kind: Secret
metadata:
  name: sharerr-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:yM+Hu0jh1S44ltOc9JahkRt7KRREyl6x3f+jGPGxQ9cxiqXJT4aenHbJ37pqYOJ7FVd69VB/Z1/XKHqCxLFTaxWZ8YbQvyhbCudofPlSyYOE3NUfYJOsviBSAsEBXCVmGnc4idCUdWV0Nra6YixS8RDhIhq8C7TNb4aJY+JL6ec=,iv:UALIVN9lYF7tUJ9RLTAPBFACfJVbXLrYiNFQFvxxhiI=,tag:9yD0vVVG+u9QId3f9EMNNA==,type:str]
  PLEX_URL: ENC[AES256_GCM,data:BCZRCbIPn3OGVkuFt6D1RJW8rqAkVzW5rxDyZtYOn+zcoaK8Nb7iG1s=,iv:wXArYGIBpHlEx6rZF2Qigg9Fiq+FmZ5UN0TUfpJIw+A=,tag:V+E3cyYVVM1DObqba1GvxA==,type:str]
  PLEX_EXTERNAL_URL: ENC[AES256_GCM,data:0OKATYhWTfS2ZPiPpSEbDQmhoqlg,iv:5uHmMkrbWoE49sBMD2/xy1jhsAYmv1lqxp7AFjBVFG0=,tag:PcTdraGuF05EoMm5yYaJ8Q==,type:str]
  PLEX_TOKEN: ENC[AES256_GCM,data:EhzjPVANy9oX7NCCCvnh1M9lefk=,iv:R1YSUtufGij5yxhLkpKHDE1m+lJ0xka21XZRd3FxyK8=,tag:kmsuW4kX27p2Q7soAcXZ1g==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:vgn3dqkDqTdN3/LcrDgMyxuI5WJYXc6yE6q1P0vKlAm/0dfyGxEv9jgj6Hc=,iv:o7WSnddpweV6fBPRv5qNPkF2YdEQtO9YEfEEs8sJQj8=,tag:htmg6iuBFmPflUs/nFL2Iw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:i6JoP9uHOgpygIcImUol+tWw,iv:8BqO3Vit97xRwXpd2hCgjgw8/zJguGtVlkgIOySwyFY=,tag:cJp+uj/eizHN3BlOUT0J5g==,type:str]
  NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:B+XZ4mEOjbrGPRTBaUuZK6jocMg+TAJX,iv:alpH4hxRcGMHYh5OYdoHugMI/dBXHIYOJAymRe0s7RM=,tag:Ju1ziNwddCkJc5f5DC/kHw==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:emsK6x8O1qyNKg==,iv:duqao2+qHqhZUiNqPdxuiQELFGbADPqmRIW3/rr/fgE=,tag:/hgeTxH0R/U/uZrpy3TEgg==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRVN2SHNZcWdjeVQwZ0E1
        SHdKbFBiNUNKbndHbHVpQ0EybElMQTdxTkVNCkgyY29LRFZyYUEzVS96T0hJK0lK
        MjkzeWMyQW1DaithSGNycHJna2ZtN3cKLS0tICtnT09Kd0tGTmJpemVyRDlkN2xE
        R1NzbWd1VWNhZW1KRTFFQVcyM0E0NUkKm3PyicIT56dXv55b+pWqhRTTyTYyk+4O
        9JKGbH5ak5R2F/uafI2+bzq6JfSaWFqngujTpm4faEHWRFDhVRKpNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T21:05:59Z"
  mac: ENC[AES256_GCM,data:J2CdH5FZ6ddvRxHwEgSYVtfvQl96w18kI9Zp7lK9XZMvDGzWr+FIqQZdOeIfeScgBfaAj8SmWOXze7uwYdNjuqroH72UgsMJQrgt/yd6lyQTD6UVG9EoBYjjrkddjAOP8fdkCQe0ZzVQpCgngOs9WtVqZleWnpVTo/Id8dqR8VM=,iv:5EW9TYbMoclYIMqvNKvqkUSWajr7pCbkeQw9ImXLSdY=,tag:T2FDu5ky1itQ5XfAegs+MQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
