apiVersion: v1
kind: Secret
metadata:
  name: sharerr-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:2vCOkWF8HrUUVmMEOJofAOelSXTzopFYUzNzVC+MXKC+ff9AaQpWukoVcxVv2dXOTxI1eQ3tOoTzjkb2zda5aDux/a66Bh5nPh1gHBuACHGjyj3EOvcNOJIv9v25+t1oq79g3p+LAmMBP/KChM0pr+e3AfD7O8WM2MzXaN3204c=,iv:NZn3YxBDGQFLW40KAhCOGmmUWu1LZJmRwpRhj27MjaY=,tag:G9MX1QSTsfh9+LORML0hPg==,type:str]
  PLEX_URL: ENC[AES256_GCM,data:SZyrQiTlWgtdBXmVwIpIHJgWOMrStE78wnfIGMOWh46IutFy7SFKmMc=,iv:kEU6wShdC5GbhLU5poVw+HnUu9WLUsJgtyCiyoOADfM=,tag:3fOomGSmPowuV3fWSeDjdw==,type:str]
  PLEX_EXTERNAL_URL: ENC[AES256_GCM,data:ryTGm9wBaB9JoDz7ztswBdfvnHlLc/5K7FsYz2Dj,iv:vfQBpUxKXICR06rVsmuqC07f+F6ErYJmuyzrNRIhlfE=,tag:1ThjwUMOumESFZSJ/PyHrQ==,type:str]
  PLEX_TOKEN: ENC[AES256_GCM,data:51c5hWlG9iN7rOQerdd1E1WVVX0=,iv:2SRI38BLuzMpGgZlQJOliJMQLCN1nyVYH6PX/pju+FM=,tag:+o1f7+Syc2yHe2Gr1tBgLw==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:Ms7a6QXTfr87QssNXAKDUMntNbQGJrvLquruWPjQVJGpNZeuXaK4lfxVSrU=,iv:r1C+Iz1dj2S3nUOG6gbe3uwwmoyqX3DXG0OwbabvcRs=,tag:gIwwL5tVrm/QzfxD8MUfDw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:ZMZkCxzQN6AucJyK0vN14L5h,iv:zMlVO2FR1leH5dFIV5blGWO3Wggkr73SIC9Zpvb/Kn0=,tag:V8RPwl2lDgqcumctA4g51w==,type:str]
  NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:t4OVCwndzufkLGN8YWUXivCaTU99n7kt3z1d,iv:KPBTsWecfX1+BqkxmoW7Wkz2PcHhg19//cMR9JBJm54=,tag:VWNg8W5hkXTB4pQY1Spd6g==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:+C91Jfq6m/rANQ==,iv:iXRDaNQ8HaIcsWF/MK6c1dK01zeC8k1QMd6nmGBUpos=,tag:uPw+o7Sfr6unhBuUVkTb3w==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUkVBMVhaZzcydGU0NzRa
        c3ZKUGhPeFlzRUMyQkJnb3VPUGM3ME81WENVCjU2SmM4UGVkeG1Uam1CeHJYeHdo
        eTluMWxtL1A3SHNPOGIreThmcTVlUVkKLS0tIEFuUnRGbFhqeUJkUlgyODJjd3F6
        eEZOeVRUVUk5VWptL3Uvc2E2M3hHR0EKwZgBxT28/uevthkb4f5RfJM4BNEgwuDl
        AOOQko1UTEJ+u2mpTMW3OzwLn0ghRC1J6SKBlQfWlkQKB7fy8M4ugw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T18:44:07Z"
  mac: ENC[AES256_GCM,data:wjYreMai6f7ifGDb4bhP4K+Z/uLT4YYM9+bx5NR2bHZ+39A8y0TcIeowNVPCZK2L0VgMvQASs/QZmyO0sx+gIYPrnG45mEY64OCr/eZTfPYXtiYXHoNX9hIUeHL/vZE950MpZ47U2w/iuBVAGZPWrf4/b4svLYVot0hkDrra2D4=,iv:9J9tBTKzrt36Dx3E/wA969Z+RZ0PJ2XLvk1piVFxdmA=,tag:lZaXPav0TCwwsHdgZsCn2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
