apiVersion: v1
kind: Secret
metadata:
  name: sharerr-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:GH4R/XIlc3hRiscedlORBjTjYq06t7Mb/UYX0CngKoasUKzUWFh+WA8dxM2tZAuYWOTLg8jzbrzCzBmrLoqbatvj7YJJDm7F/SDzwfqbuzSSNChrGdP9fr6maPBPsueid4byXHpfDu868C7N+OlX8TDo2q4P8dmHABgHuYMY4eg=,iv:Q7wL8bKRdHxugc06VJdb6kg2uXIgN6XC3Js3wXXpqag=,tag:NbKyLsiwclPnWWEzG1fMPQ==,type:str]
  PLEX_URL: ENC[AES256_GCM,data:6TFwNvWeMEUM9Vzox3hKRyE+22Nw4LHJu4TFgKx/xmSPd03XjlJotA8=,iv:zSGKk28RPhfV7LV9sbSues3FBSeYaOgxEMt2uqBQidw=,tag:MT/mt1LAN9R1p4AHpkgrtA==,type:str]
  PLEX_EXTERNAL_URL: ENC[AES256_GCM,data:XyQqIgObVQqCC1a16V4KILy5VdcDsvaOUm83PLlS,iv:eS+em1Pq/8TZIbAqCZTU9DmPIMDLSqDo3TQnwfP406A=,tag:XvhyHAc6QV2ObkjGVldcFg==,type:str]
  PLEX_TOKEN: ENC[AES256_GCM,data:8IavfXnSoP4otC7k1jOObP9faMw=,iv:PqyNIhCXB3qmmPwH4qs55rgakh2faGQcp04PyzyLkvU=,tag:OOqRXZaSmIucL1I7dte2CA==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:cNiuBrh9+temt8+PUHlgZ1e4Mm3Ii45KZjGDzotN0YdLKobT0VzZFG0zU2s=,iv:whyik8cBke8p0vysIPhmlTcyNc/tC0vY7zzl7BCsGV0=,tag:cnM0Ui+tHrurLFiW7SAm3w==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:Ac0pSzR4i87IUj70e6bvv+1P,iv:vgYC9xJ++6S5HOeKr+fFfacShvdSuF2UE4b6bWzMuxU=,tag:v0jUd5tDAaayrTIohCrB/g==,type:str]
  NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:OPKBY7cRykTjvJsrq91OApNQLEovYVhh,iv:L4xNkWf5d4Jvp21IXANxou1d+0NIiR2TylIQExVFrmQ=,tag:egclrrcOFqmmuPaFEE7ohQ==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:PpMoGbDKM6GHIA==,iv:tjjK9nkYKtz/znCCOv/WVeI76hZLbf0RiMzl56ZuG20=,tag:d+tHZ+OYPGAuIE96ybkgSg==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WTRFdXp3Y3JVL01qL09X
        NGU0TzY1NElHS01kSHVtM3NhMjhZd0gvc3pnCk8zdEZwcXpERW9ESHhaWjhqNlg3
        NXVKOWQ0RDBmREpCMDlwblVYQ1kzMEUKLS0tIE91VXVvUExpNHU1Kzl6cmpyQzZr
        ZG5lMm9PanVLc3M5RW96WXFHa0RKb2cK08sPS8wpm3H5SV12QfoKcFIazVRofOog
        747fqwi7YGxxwxb27Xya09wZz2VFpVhy+lqwMgu/mNlDjy4p9wO06w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-14T19:05:42Z"
  mac: ENC[AES256_GCM,data:fMjrH/pC+QbvTFW9MwBXeFGRYR+hw8rct0xAYSMXC4itUUy3epzPBRU4KOsdPvQxL1BZ9Gh2dxirZdOR8XOA5SM/AiLbvzT2m9/WLas9pKQmkRRoN8OHvdIVR2k4gAKaVySO66f0VYQ9fmgr5iZm9ajwygVp/BGAVrFzc/XrIr4=,iv:Qw3/VA4qJST9b37Q7DyuhQR+hpdhDA0T41mpxZXiTPI=,tag:Er1cBtX68iZzNAjKxrb9PA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
