---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ilo4-fan-controller
spec:
  chartRef:
    kind: OCIRepository
    name: ilo4-fan-controller
  interval: 1h
  values:
    controllers:
      ilo4-fan-controller:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/andrei-iacobb/ilo4-fan-controller
              tag: latest
            env:
              TZ: Europe/London
              ILO_HOST: 192.168.1.175
              ILO_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: ilo4-fan-controller-secret
                    key: ILO_USERNAME
              ILO_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: ilo4-fan-controller-secret
                    key: ILO_PASSWORD
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    defaultPodOptions:
      imagePullSecrets:
        - name: ghcr-pull-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["fan.iacob.uk"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
