apiVersion: v1
kind: Secret
metadata:
  name: ilo4-fan-controller-secret
stringData:
  ILO_USERNAME: ENC[AES256_GCM,data:WkXUAyn7O7I8nPKYIg==,iv:i5lNIOWNs6r20dn4FUVL26IeRfRb3wxW0NFBpaNz+Nk=,tag:aDYtb8I2vzq+5W2NafZfEQ==,type:str]
  ILO_PASSWORD: ENC[AES256_GCM,data:15npMaEFNC8=,iv:9sCAHwAKDWrEtXTmtON6RNsdix/tmvfOH8ogLwEuJFo=,tag:kb2BwkPiX/SOTwqH1elDzQ==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVVo1dS9RYU5wdVRkbm1r
        NFVBdTZtUnVDUVZkWWlsYVVLdjRXcURyVUJ3Cno0S2hQQSswdlgrb1ZSaWRIS3pz
        NHBGL1JoV2RqeE1nbGFIdkhyUFpiWG8KLS0tIEZkVXB3Mm4wdU5tYnFiK2prbjFO
        eThpNEZXclBXaGpoYWhxVmF6dDlFQ1EKlGTpPWcz4WOC/xg/emaGw3HuOm3eYc8T
        TnFjAT4CNt1h7ORscqh7ml/xc4QgYnGHcVvmAy8ExiAo1IbVljfh5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T21:01:40Z"
  mac: ENC[AES256_GCM,data:lDSdeuqRbIoa+oz2k5DL1Qv1TcuCtiLv97eyhx3U/C+fS1rEQhb7/Z0680N2Khy9YumcuKL+zaPt59KcZ/dFcUlU2qOxb8JvmsaT0YGcvoBgGUggs1uwUR750sN3KInrxTOusCR4bGlYF1/RKiTogsI5kmLkTmfqQ7kWP9ENRzM=,iv:MeGBI4VMot6sHupeRJnzGfG392qXgMA6hIkQgl49pl8=,tag:T3Q4AL5/jwI7LEA1lbo5Zw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
