apiVersion: v1
kind: Secret
metadata:
  name: planum-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:PzcBfi83h62U/DshBzkeBFcwGaaPXvx7DHajCqP6B39frckOVN58jcCU7AoQsN5hRJiG6eDr0CUYQxLfwooMK3j2DgjqKNC4RoY376ln7qpX2ji59yE6fgp/D9G8OUuAT8Mj0Q==,iv:wiEPZ8FzGoP/B3B4nEb3Huh3kGbtoRr3KyMJTaCSZYE=,tag:I+KpbkuXnQ00O5ug0PLDZA==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:UOcGzyOlitlHkSm4Xe1m5zYYxP1MaY0ycl1Y0NhLrW7VMT/AEErNyy0c7wSE5dR3NV7G7PH6gRVgueavqdJRkg==,iv:N2urh5F6/H2d4uSYSzMJfSh8anJhlJdEPqJb+cK8Y1s=,tag:YzJew4fG/rEDzLZU+By4nQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxa3c0THRiQ2VhSldVZkpM
        cUlKUmRveDRINkFHYUszaUtLOVE3THpsSzBjCkMrZ1ZiNlEwT0dseElzWTNOUXBZ
        NE1IREhyeVBkUGpUK0tJOENERFdKWXcKLS0tIC9saGdaQXlVTDcrS2hiUm4zK0dZ
        RG9yVlFTcEltallRMll5RGNZYkZJQXMKnldXI5Rew5Q5Whtu3DMrhBmkVnPAgmmL
        fRZn+jIeG8w0vDZH6okHi/tcrSv1rcP+dKl8+lk3atgX3+L0aQtCkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-10T12:29:19Z"
  mac: ENC[AES256_GCM,data:cBOydh1sXORDQet/II2EHFM4gSWyfypf0EuiPyDPzVWEuuimjZjfLc0maGILu6lYh0bKQcDxB9SETHfN4iz3H86o9mJGLqfyTZ2l7PIaaQ3LVGrhX26mrT+NEvToA1ZAZWSIeBwfk0QE0umyXYMX+IUz9HI0xDKf41hSb+rSBh8=,iv:lIX3z6+RUXbQfPKpOtDdWFPnjIwBnQydZ79Tu4bqKog=,tag:KNZzcAUGc47Yrur+lw7Pig==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
