apiVersion: v1
kind: Secret
metadata:
  name: zipline-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:pqa9oXM74+DEW5OIrTOOvmGvOHsPPMxtBZWVaUORerStGY9iRMMhBXK3xv3crU5cczjf/xT6GUgRX/LGQnpgXmvuRLHM4007NOqFEauBFLWy/tfVZkNb1eH1xk8VPZz5/5xaOrL/Wg==,iv:iO1jfm2srnvoRda1AG6+YeReU2plyfsfsL5Jik4vxa4=,tag:J0NbR1h3azcr0TJVmWnkoQ==,type:str]
  CORE_SECRET: ENC[AES256_GCM,data:Jp0tOTfL47IJPIsd7H1MJKrWB9Kq06fH7LXzyu21nMhg5MJ0hOcsG8r9ON8=,iv:ELFhFKchHySBdK8MGQ1fbV5Iezg+rWOlH9+aa4DqA6I=,tag:KxeI3Z9lSiVWzyK72qk3yQ==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNTVuYjVhZlQ1eHlnWVE0
        bVhKZHNzbDlLeHgyT1BwZlZ3ZGthdjBSOWt3CmRPSVV6T2xiYWFVLzM1TFNvdmlm
        elRUSFBIak5jdzVQVHJZT2R0SFFlZ2cKLS0tIHFZdVRuemZhczFvK3RXelU5dlhL
        NVg3UlJUQlZ1ZVpoTVVBN2RuSXFiUjgKl5/iZKG+Cvz3fJgPx66SmnDWzMI9n2B5
        f+2xEwWeHhbgmvfSMRIcBf7Sa+r/pFwEo8JICVegUplzdwxn4dQRRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T14:54:29Z"
  mac: ENC[AES256_GCM,data:GJpriHWRAn0YKxLSEhkLrwzg6Nr09NlxyLxGKUuy9c4p8in7fP8ubiFMZMQPRpszSjpw9S7qiEs08uHphYyV70P7iVFkZOoWnG4l69HV04NyYSSfYpsO7MZMdG6Fss7ClYeWSyytmXsk1YlSECwKhpsDwZqdxgDN5L7yAvIfcjc=,iv:3uoDcFGJ6iqntMFNyFvyc0OPptC6wg6cTmnB37Pe9eo=,tag:oxTItqzrNYsa+ZolXfq4Pw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
