apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:3T2iZeUf0Ym6B2RVZFvCdGpIYYwpct8jKWtWYO8ltLi25OkLy+/srGBbkmjzBkGuYNn/jbE=,iv:tPdXeiQZLdMa432zzx2Gcc7iQ3KPLfiSswgWPoNYqRQ=,tag:aJ+nv9UKIl8IOpo8ZMgZSA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WFpmRTJmREZ3bE1KR20r
        cnBRMDNrTlFYc2VIeTNFUUVFN01SZHRZeGtrCi9MS1V2WWJOQnhGV0ExZURRcEZL
        Q1E2ODRLWXVNUENqeDRZTFBIV3crZEkKLS0tIHlMZC9jRkV2cWdLU2lvZU5mNVAw
        NEZSSlo5ZGxWQ1ovOTRubE9jeTluVDAKzl24eLoeSAU25tNsw8fLLlUsoMWZGW66
        N0JgX63mYG0sOzaVI/+vTL5b8J7W+6asi9rdp3i9dn8LOOqycXJXyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T19:24:38Z"
  mac: ENC[AES256_GCM,data:mFyzfDafo9hmkqNWeUIkmkQK1uEA3Qtz0mXbmq+jwwkAqAAO3bO+os6AwCXboaiGF29V2NvUq6LUOGN2D502wuxo5lEIrytCm9zHweylHpao0aD6Ss7yhL/tnsDgBMG8EsmZB5lulB6xAN8u3lXykMw0GDRjSZEs4GLS6WfOF9k=,iv:Xhx/Jk2hFyYpx5EpM9xsp1Uy1Nxi0gfqa8i6IatwpOU=,tag:Amtr80OjBu3HFFoaNPhk/A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
