apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:3T2iZeUf0Ym6B2RVZFvCdGpIYYwpct8jKWtWYO8ltLi25OkLy+/srGBbkmjzBkGuYNn/jbE=,iv:tPdXeiQZLdMa432zzx2Gcc7iQ3KPLfiSswgWPoNYqRQ=,tag:aJ+nv9UKIl8IOpo8ZMgZSA==,type:str]
  api-token-iacobapp-dev: ENC[AES256_GCM,data:yutkxc8YPDdGmcKSL1bHwOHZQzg1uO4PVBT1CiHv6Db0WQGyoL46qzHpl+kPDSsCehokzK4=,iv:qKXTKVJxBGdVg7sOOiczeEpxZgFxXqa2xVLOsZqnuzw=,tag:/R3F08b+SAHBLKLL+Zx1FQ==,type:str]
  api-token-iacob-uk: ENC[AES256_GCM,data:1ZTPPxHBC2COcsFHnwo0EJSPPXgQ3wXjVe+meX+EKQj/lrhipQ8GxfVezhCocgxT2jJ/pVc=,iv:khxYZ5ceC5a+nzYgrfLFqBxYztKwIoUJi2UN/VNSQEc=,tag:rBDzICRE5WExnE5RcDH/NA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WFpmRTJmREZ3bE1KR20r
        cnBRMDNrTlFYc2VIeTNFUUVFN01SZHRZeGtrCi9MS1V2WWJOQnhGV0ExZURRcEZL
        Q1E2ODRLWXVNUENqeDRZTFBIV3crZEkKLS0tIHlMZC9jRkV2cWdLU2lvZU5mNVAw
        NEZSSlo5ZGxWQ1ovOTRubE9jeTluVDAKzl24eLoeSAU25tNsw8fLLlUsoMWZGW66
        N0JgX63mYG0sOzaVI/+vTL5b8J7W+6asi9rdp3i9dn8LOOqycXJXyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-25T10:14:20Z"
  mac: ENC[AES256_GCM,data:XsJ7lsx/bzO5AECdzGW6qpN+nOhdhLHlfn/zqTIUi2NY3c9Md1OOyOLW4y+8+5O1+2uUpNVf6U5x6c9Oo6oAft3OD2bK5ILDxxW2/PuKrEysnKwmhgRgXAxMkEYlyg8245HOUvAMhr6PqPJE0cd52oFwIz7qPPFL7V5yX+VczJQ=,iv:dCdhPkzRIFK5+AazkbbuBVdgPLHUeE/fApOM3c1b+PY=,tag:HQUHhVE3fxQmJ/IZfRRZQg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
