---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-clickhouse-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-data
  resources:
    requests:
      storage: 100Gi
