apiVersion: v1
kind: Secret
metadata:
  name: plausible-secret
stringData:
  BASE_URL: ENC[AES256_GCM,data:gnkrn3Zfu3cvtRbwoRXcMInWTnWsvYskGbiQyzs=,iv:F7zTXUeWYvRD/6qrv8g6rD++gdzpw5paaob1YGk973Y=,tag:AJdYeUQK+44KCXxfv9uKDw==,type:str]
  PLAUSIBLE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:l8iy2XFPY3b2ArMZzaXQyhskwDMpJz2F8g5156ChxgxaQBeFOgp6cA==,iv:PWmyb7qBIIYuDvTQxl7SF3FnD+e19g0zlOWinqkt8ps=,tag:NCFMY/xPTL4n61KyUcmC9w==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:IDi8k4KTeyw8d0hwf5jeds4ksBLy209MenCJmA2rFmJnknrfK+j0trO89ra91YBCckr+csTaTO89iFakmY8kD8Tf8GUx14tiJ7+xQz6HB7UC57+VdEJXwWi0zxGhmOmKjL0DzhJomWOojtG/sl0YKg==,iv:ug27onf0zxUBSjMznPw2tzyHlQZjnQmpa79J5NayHFw=,tag:QCee1MuQ58Zn73BYWbwSTA==,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:kvpz4o1O+zjNNSkw9bnKqgZgRZ4iG0Stn/P2TZ8HRSMFiAN6xIhoO/Je5DaaiN/aAwBo4YJtOfSQY5Du0aQ6UzzhFV9OEdQWtkTx3WU4jlKSraqX/kkXnQ==,iv:kcrCXqzd9qfXwxG09wrHFGRlSAt5CI9XM6Yfist3yW8=,tag:FyES1wuHMJ6R1KmwJBtRSA==,type:str]
  MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:tbfUikvcVSwpBktF5Me1j3ZPfmgQvFABnjtBt1kCfUoR7+DcTNBtxg==,iv:QB7S7UeWtNvFlDaiP+gafDBA1FTKsANNLcQ4MA0LwD0=,tag:DYv2yq5IXE27nKmA/cELtg==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcTgzbnpGMmRQL3U3cUZ6
        ZDZZVHY0V1lmbmtrUlk2THdpdWZzUVZpMlJBCm9BbnVDMUJ3SWZxc0l4VXJaZ3Rn
        LzhWMDVIdlFRS0NjYTE0UlpTUU9XUUEKLS0tIFNCajN2ZkFyc1ZFWi9HbDFhbHVk
        RmRGQXRsRnZ1REErRlB6cUp3Y2hRdkEKAJPb9QYvamw4W/gPoS+zR/Xa+hUG+SP7
        wR88fwGTQpyM2CAxG/DchXUCdfKu1HqTX3dOG4kHlravhn3vyTr43g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-24T09:38:37Z"
  mac: ENC[AES256_GCM,data:CR+ZJkyJB9oBKoNOfGNkgba9b+ygWKtyfUD0EiKXlMV/F8OO7PBC2MzQsKnIfW5tENkFPcOzpFsyQ6KIj5eVg/cgdoKfAgaDwYQhcNYoD639iSBoWmAg9xB66aZym5WEZlALgdhi46S8nSNqaLu/ua5EfLbP8l7jA7VbtoqLxM0=,iv:7eVOqxqk8O0NipmdORAPfxanGPvO3VKZ0WtBKeRq8xU=,tag:43L05Cw2ayseSFMSTf+ABA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
