apiVersion: v1
kind: Secret
metadata:
  name: forgejo-pull-secret
  namespace: ai
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:6231mu/4nT5OuZbaQMelM7/BZVSY/lLtuBSR4edcUg9hbHqWu9u/n5IKOes2ejfHcqxuPQyIuMkvIpaBtBUTACZsm8HRRGzAd7TcNvJlyH4tn1Z/UlVQfBwmrztrVMUMvigSUAlAWVU7XCYgFImRoK4+JjIE3EgPdfHBqiq0N6MUVRU2Q/i9ULvUQ8XpRM4pwfxpCZK58h98GWRjYh2e63QkMwuZiYLFoBMFbjYHVitGw68P,iv:pYBhENeP322a1pykbM7CH5e6sQQsUelJXMCuRvrsCEI=,tag:2Vt6VgmH7QXo0zssuZd4+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV3U1UURycEdqR09ubjJN
        eC9ESGhQREp3L0tWWUNVNExiOU1leWluOVFBCnFWOWdJZjFwUVIzbUZJWUVmTllC
        bjRKMWxTTStmSDVHcWIrdllwWlpQUUUKLS0tIGd3RkVvOWJlY3ZYVkF2TFErR1Yx
        VjcxMm1ZcEZRRno0UlNmL3dqb0Z3bVEKjnp7nD7m0LUDLVhI8zZNpjExdgq9uQQ9
        pePod9y0OT1sIKX8pwSISVkF5C3yfPP6Cl/EZre0MKXD7IqkOzc3Ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T19:07:57Z"
  mac: ENC[AES256_GCM,data:F5VY+bS4LLaU3K8kvmQqreRi1F4YC6sitiht3xkQiLTrGxq3IZJ05qYMNFNU36YEl9RUYHMJysVpDKcyrEzV0PP6vh4IWZal1O43ZV0WGnQTdsPe95J+L8qA4azHTAX/jCKiAjus1l4YqC3npqlAmsyC1LDkg9npEIKddTq3NDc=,iv:8LQKkKQ+aPBRgHHfPFu80nij+12PgTZbJuRwCqWaEyE=,tag:S7F8BxjrRfbFl29QxaYHJQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
