apiVersion: v1
kind: Secret
metadata:
    name: website-secret
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:p25WreD9DWgFMNY=,iv:THMm6IMZzyDY9J9dhSI+zNv9OZVgm8Mtw5lPWrB5lbs=,tag:Ae8LMBRPcVuEzHCbizzEKQ==,type:str]
sops:
    age:
        - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUzl3dDhuZHdqOEVUSjRE
            bGRIYzdkVXBPb3NyamNZZ3ByYU9XelpYVlc4CjdkclJPTDhRcEJuVm1lMnMyQW04
            b3VTMGVwR0loVHVRWGZXUWRleWV0RXcKLS0tIEFNNUtBUUVjNmVTWUF2eHozdVJU
            Wjd4OXQvWnJ2em5mSXREbnIvcXF0LzAKOAUK2txZ08xoB36rMIq3C7/ZB1YW/XNG
            9TI1/838oYj2o39hkOVE+tpwI3mirPWE+8N4X4xJsKvARwQFpP3hvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T22:00:43Z"
    mac: ENC[AES256_GCM,data:gTmjQwdUb+NO+mmmXwkgEYR6CfrQsBpDCqwfGYbgEOuVxWJbfeGGthuax95H7x2MAqZ+cnJj4emhkx8z5cj54ejNFLsNUIrew9CJ9DA47xc25zmpIXUsysq7R5YdeSklDA5IrP+pwQ+YJUq39LHnIC66lahC6DsGcpZN01bS4gA=,iv:rPq0QKGSv2SiF5kefhIJRmg+MzIyqMygHFlS6PWKSSE=,tag:hcp2sMJ1PAsj5IDt3+calQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
