apiVersion: v1
kind: Secret
metadata:
    name: website-secret
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:p25WreD9DWgFMNY=,iv:THMm6IMZzyDY9J9dhSI+zNv9OZVgm8Mtw5lPWrB5lbs=,tag:Ae8LMBRPcVuEzHCbizzEKQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:iNujxj153FwV+AySSmhF3BXHknDRE51QMBYqqYKMUbVg8BOP3gbb5w==,iv:c/AA6IkTEzv2Bnc4N38nF4gxs4WJfnvW9gPMtrTh3Wo=,tag:8gzItV2LuGs4/eC9zhYLYA==,type:str]
    FORGEJO_TOKEN: ENC[AES256_GCM,data:xIfEDOXE9cMZ07B0J/Lqt96t8SqXnBYHBzngdItsKYKP5bmDeg3xDA==,iv:CvRNQU6goco6abJXZ2tCemlfrCGO8qzUvOGVckGCVgQ=,tag:kfe9+tzzpfkIdWwES1zuiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUzl3dDhuZHdqOEVUSjRE
            bGRIYzdkVXBPb3NyamNZZ3ByYU9XelpYVlc4CjdkclJPTDhRcEJuVm1lMnMyQW04
            b3VTMGVwR0loVHVRWGZXUWRleWV0RXcKLS0tIEFNNUtBUUVjNmVTWUF2eHozdVJU
            Wjd4OXQvWnJ2em5mSXREbnIvcXF0LzAKOAUK2txZ08xoB36rMIq3C7/ZB1YW/XNG
            9TI1/838oYj2o39hkOVE+tpwI3mirPWE+8N4X4xJsKvARwQFpP3hvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T13:10:30Z"
    mac: ENC[AES256_GCM,data:e7aionwN9szCkZ2gVhVZIpSXQvizV58fK5LBJXZObEMJ2w9AEWLeXPnL+/butZkmRJ/cZFY1+F82NAkV/1dAhinjYOOoFXikOGAW9YmHCpnIo5FqRzn1cE2Y/KN184JLgtKtpbkszdjrnls7WhRUBklKixTHz/eZE5DicC3hwp4=,iv:+sLakZ7ioyZrYf6NGkpm9g/kTKAi68e3+hLjGAXo4yg=,tag:Fc3kYnU2mIkY4Z1/QBSsnA==,type:str]
    mac_only_encrypted: true
    version: 3.12.2
