apiVersion: v1
kind: Secret
metadata:
  name: cliproxy-metrics-secret
  namespace: monitoring
type: Opaque
stringData:
  management-key: ENC[AES256_GCM,data:ie6NK8sUXEcs/5+8Hp51kiquxc6hePcFyG8N3tjBXOETqrR399wDq9VsZUzShj0r,iv:3SjSWRRNYekvJy3lUhjTciHOWJ4aBQ92o0OiIFlTgdM=,tag:HO458DxIqA+X5iBVo0bquQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbi9TZUJjSzhuVWVVdjhX
        OVZRUWRob29vRGZrakd6SXRRZE4rT0RzVVNFCjd3aDZhRUhHTm9ZcWZKcmUySzN2
        YiswanhpUUJNRjJLd0hDZDVoMENlOE0KLS0tIFJlN29OeHRpU3ByMVkxa25nZXhm
        SGkxY2s3S1lhakxYanllcnNNcmt2NXcKXaWJVrCtYvN+cwuUL6carYxMb5NdoTXk
        dkrjOhNH5eemGHsxvPbE5AwGquOpFpGPS24oiVO6zRPdQuA78W35dw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T18:28:16Z"
  mac: ENC[AES256_GCM,data:ygLwtZrNf8oXfpVaILKM6oZYQ9eF32JKoPh8VNRj027WoNLPtD94yRg9vQBWH9c+9EQi3m7vxWUz8MlYDevdFDMgeGzIJz2C53QSZQkndewo/DYKDLCN2/d0Ucvyrw/h60tQZUai1Y0lM5Z+jT2rznw0vzHpTsqNWvaA//39pho=,iv:/jZWKlM3WtHPUXF+N1hIXP+qesKlaGV9DSPB+YFZYCw=,tag:ISXYJv1NHcKzwoUeK8EtCg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
