apiVersion: v1
kind: Secret
metadata:
  name: mealie-secret
stringData:
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:EinSjaUuxzfzcTTvgKMmdt5e6YsvDJ/XJTXwsBpJs5/iDTBLpMsyKJslc/5es08lbOPexZ7V9Lkc5dFjIILE/w==,iv:LEWBVp1ua+t7CA91F63dnrmG+BbUCA0jnSX/8K3HbkI=,tag:zMBwyZnwsFYPa2hZ4ja/1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VnQySXU4a04vYk9KelA1
        WUNFOHJpSE5OSmN6bWpNcTJ0L3BNa2JMV2pBCk9jWW0xZDIwc2pDZTJZTTVSNzhx
        bnpESU0zRGp4L2hXSytuQXd4ODhTVmMKLS0tIENnOW8xR25UanJpeTJBM01GVjUz
        VUZGUkZObURGckUvdFgvaXBsZUV1Wm8KfzU7meNSjS7ZQsNMONxGcJeKYeyJIfkT
        blR1iAHUDarvyxhy2SJqqHxhB2rAyTfp4mfYlkRITGqoY14sgns6Ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T18:09:48Z"
  mac: ENC[AES256_GCM,data:2y06EZcH/ok8b8dvbh0NZzwPdhozHg6Jj1RpgQTJp1vo3KbkMUifTEYRUe+AEPizyxIgt9Nw8yvvooXQge9EQ1xt9CoXLmkHoWtMLFooTSfDHSv+rL/Avp6cM2MhAu31VJYPh2LofbTHZ5RiJqoyghcyXC6Bm/bfn5ETfn6GG8A=,iv:v8zOdUdXcHHT5yq8NXFtbXPm3ehQ18UVMXVz7fpTIOM=,tag:AezrfsOdwqaTwefDwfmLnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
