apiVersion: v1
kind: Secret
metadata:
  name: homepage-secret
stringData:
  PUID: ENC[AES256_GCM,data:0RCdog==,iv:ZZYAw/QxL+eKAwsRFASASkT9UTkKSnqKbzjCVEjhL2M=,tag:a3REvigmnShrm4LaeSP+4g==,type:str]
  PGID: ENC[AES256_GCM,data:RnC9SQ==,iv:4SBGL2KQewlJkuKW5A2IVejUz+8tLhGsRnsN9gL44rI=,tag:fBGuBP0UOg2RNvIwiVQd7g==,type:str]
  HOMEPAGE_HASS_KEY: ENC[AES256_GCM,data:BM74f3MLWN5pz8NKlJjTUGMwdqDt+t4739gJPWV8zChHw3AY7vLhLGDhggxBAdtFNB0bvlFv0BbWGKVy2fOoySGtRJOC1SOdh2bETwPdLDi7GuuZPtPaxlJkXtgCuYTkBc8a77NerZKljZkrjrJ/wQ4XNJGdZRj5OgbK8z2likgD4Jv2RScTvgk6Em/Gx8dj8RF2AiD4k7CStgOEN2NtXF/P7TeQATYFGVcFjSr1rCy8B5pPadeg,iv:YkUXoSBsytux27Xeeh6oJm+3c/FW5VxVqdUyM9vunos=,tag:kfIKs9QF1+H/wbV3UOPvcw==,type:str]
  HOMEPAGE_TRUENAS_KEY: ENC[AES256_GCM,data:MrjxhdZKirzhv4GYfzUY8CfK7uEIqoV2dBMq1JfnLHAXMixnpJSHaC8JXDiemd7K222Yc06y/7KKgq+GKBtGI8bW,iv:TaUuZraErYyhZe4IgQh2kKOubLg9MC6UWNPulQsfMOs=,tag:PzwNMxQzja/5XynTx9HSCA==,type:str]
  HOMEPAGE_PROXMOX_USER: ENC[AES256_GCM,data:FdI/ZuvKSq1Je82hlexmclo=,iv:PmtsflQp4v2wBYL3duu7HbAbV5FpoHnc79aH8Ei9ovc=,tag:jpJNP70Q9Rt3a9q1yem/aA==,type:str]
  HOMEPAGE_PROXMOX_PASS: ENC[AES256_GCM,data:5XcYmiGYmrFZzEAAv8diOQxVGi+HxBM42ovlnI4s0VdOjrMH,iv:zEumLBaeoUYZoTPzi1CNl/uqt1VVgpztcpplPXFqbNQ=,tag:YtD/NGkjOIL46p2pBvylow==,type:str]
  HOMEPAGE_ADGUARD_1_USER: ENC[AES256_GCM,data:iISQf1CX,iv:YVz+raBdkgKXIrHWgfY7MyZ6SZ46Zf1cz0HVSUfQLnM=,tag:qcUhXQkZgtEzmWR2n9km0A==,type:str]
  HOMEPAGE_ADGUARD_1_PASS: ENC[AES256_GCM,data:24SfbIpl7CXFH8g=,iv:J+iJH/OT3S0Eq2B+5bblJkM7ujmvT0bXPe3HN3xxdBk=,tag:5UHvacYDQK0VFo/ibFed0A==,type:str]
  HOMEPAGE_ADGUARD_2_USER: ENC[AES256_GCM,data:/RL61oDQ,iv:sbme4uVhVDrte7oHhyDRGOfeVHMCB4aozx1fmIy1IEY=,tag:eO4G74dgDc+H7J0PXmgFFQ==,type:str]
  HOMEPAGE_ADGUARD_2_PASS: ENC[AES256_GCM,data:pe+e3hFjPft9zuo=,iv:WPTXtpre1jwAgfoDkCkT/hwWnaURqgR/VGuzkIBEfGw=,tag:GAPC2gPCTDPuixd8tho6kQ==,type:str]
  HOMEPAGE_IMMICH_KEY: ENC[AES256_GCM,data:afZs7tM7KOQ7FASP80mI1q9Eq7UsPPhZ33zVtoKG0xhEQO8QDtyAtXP2,iv:J7XHrGw0ksVzTgWUFzrOZxM89t5/BPz2Ck8PidoXwHE=,tag:ZWQ6wlzbSh4tiLVmP5GKjA==,type:str]
  HOMEPAGE_JELLYFIN_KEY: ENC[AES256_GCM,data:p9CF6gd0YonNs5ErqIv+mrUVFI1uVAL4E1VMrEabyzY=,iv:Uwbs0e24n9dxCV4qRnTbq+Q3mn9EKWfhxzm89YD34pc=,tag:h8lCtexRX6l9no4nprby8w==,type:str]
  HOMEPAGE_SONARR_KEY: ENC[AES256_GCM,data:fmXDWDCgiu+04/2W/FkgveMQLtyBzHzRJw1ytcd/8zw=,iv:ye6RFRdNv8IcSHT1osTC+5AguG6AAJb38y+86qyNx6I=,tag:T3Qin6dKpB7VLYMAxVlnZw==,type:str]
  HOMEPAGE_RADARR_KEY: ENC[AES256_GCM,data:aerBdfnEJ55pdYJrnVHpBJU5VIUp+wOinV12EKgkZ7k=,iv:Gh/qzVspKiKbl3FRCUf8suK6x1Or3w7LPKCbIZc8Vrc=,tag:6YAPT28aBuKH3QjHi89F+A==,type:str]
  HOMEPAGE_LIDARR_KEY: ENC[AES256_GCM,data:AoEGVJBVY5Zz0ZIiNAUAykS62FqNf9O8wmD4iCnWaHA=,iv:ws/4bJUuihK6LbNB1JhSTVw7i5VvEzI+6YNhgHXipD8=,tag:m/G7MilOqXKo3TBfZ5251Q==,type:str]
  HOMEPAGE_READARR_KEY: ENC[AES256_GCM,data:fu0gF7WomJlFnF5EKxRHZDHXavPyEzJfmX+tmB5SVcc=,iv:4VVLBhWHpnfPCIaMlGUTs1ius3UXv2fTCi2BByiDRD0=,tag:kR8nHhA8h7iQ99ZFQMGDkg==,type:str]
  HOMEPAGE_BAZARR_KEY: ENC[AES256_GCM,data://z72ZFvXbvCd7yBdcKVYKX77yAJm8m3DwVqZfdrsgc=,iv:3uuq9bSo7/ZaxCwakGn9GiVhnvoKVtXDkv0wNFlQw3M=,tag:RyfDskDAQg8EPBOGUnmQSA==,type:str]
  HOMEPAGE_PROWLARR_KEY: ENC[AES256_GCM,data:HAmQz6m5bVLpVKSajeOqjmlP+VRnt9MP8TBz6smky7s=,iv:T6FzoM/PUxrX0VEASKyD3kDuiJ2bfBVrSXFLbKf9qsg=,tag:iQiFi8fAICWNSehqdZoi0Q==,type:str]
  HOMEPAGE_OVERSEERR_KEY: ENC[AES256_GCM,data:y+3FuDgIAGNrLLpawnDFqgvIcxBL8I6lwMXnyGQeXOX48MdHMP41uVIUOoZYSUKH2eE74DnwI/fq8PxzJiqNdRfJ5QU=,iv:x6u1RQgj/jg61L9Fb8UyTZMfa0Bd3z+H7FTX9Yn8x2Y=,tag:bHppzLDd5wEORUY0iYEV8w==,type:str]
  HOMEPAGE_QBT_USER: ENC[AES256_GCM,data:1UoXnZU=,iv:2e46lwuXWUumbSt8MtykTZU7u/RhYnrXDN8wh69dcp8=,tag:NTYnmgvwE51K/FEL/WY0YQ==,type:str]
  HOMEPAGE_QBT_PASS: ENC[AES256_GCM,data:/CRIhBNOSf1Viw==,iv:TBOGiebj3vmEnux4NSmRv+LnuIa4sX9aDwjOO9g91rQ=,tag:n+iyVQ5fdWhlLRnObxol4Q==,type:str]
  HOMEPAGE_SAB_KEY: ENC[AES256_GCM,data:SWLumaDv1CJo5epbmmTn29XNmxpz8GheiKZqScSUenM=,iv:7jWtdLl0NHUEVZGpq95zWY48fRnbNROPf6UUSqHyg9M=,tag:8Yk1xw9k/McnKiW3MCUgsA==,type:str]
sops:
  age:
    - recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYkRzM3pYalpGL0JxV0My
        T3JldVc1ZWNmZzV3VmZZcTZMSGNzUHJVd2d3CmpHZU5YcEVObWRhVXBCVnV1WGhB
        cDhRQkhPMmFyS052TDhsdzNLRUdMazQKLS0tIGlRZjV2ODd4bDF0cmFZN204MWVS
        RXNhQWNhYWpvR3M1RTRMdThtdmVJKzAKwqKzyFB5WZOtqO4Xn+nHG5fuG7UoYrri
        smMrQRDiBN+n4h7ZzqIJSkEDE0ijXN85LfyF8V3xWzGzSdQfKSDHmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T23:04:26Z"
  mac: ENC[AES256_GCM,data:nvaUhb7ZKr2IXciwZ9ncA6eaahFS69hruS8O3TLYLz18xww91YyL5KFnboxLs4pLcPg+AMrGQx/BzGO+vcMV0muUCgfxxQsTrRhvtiD1vOgboY2D/kX5eUoN+9NltUt9tkV7F3w2m6+Fqg2zXHFAgfD5XjFwUXY62i1rD/GkIBo=,iv:FqJUbt1Lfm9eB5qoGtl9FTwtWPMZIvf9I2JL6YBqz+g=,tag:Kd5T0K3xg2qK5NUiOxFczA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
