apiVersion: v1
kind: Secret
metadata:
  name: firefly-importer-secret
  namespace: default
type: Opaque
stringData:
  FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:6tovvUOXrPkq2RRlZOlzQYczkFv7Ced0DsNWI8f2kChFccIkBeTJyH06kKxszM9vjqQg06VFJ7y4D0lD4nsIBd8bbLGLaG/CKLZAtLwVIlFIRV7rW29ns6MpLeQ+u2P/u0wO3GtjwdicQwklD5mtvFkUWv8rREe9CNYnX4PJbmWiKBRZjv6poYjTd3VnwdM5c347O+Y76pTeCF8MZXT9pyqDJHPXIHKMfYNtxvcX2BLS1TmdEeBd7K8RIxjNKSoS7bf1lVzh2R5//YE+R/eOmec8RRr0uZbFHbkkRbZyk663Oq2sp9NPTq5rwqL76MFFMFM4+ilUqI3+A3JjvyAJP1wVrjzav7osjBcAi+yfpY14yvbGFva4BFssjjdoSEVrw+OBEdePx2iW68ByAuQZTzaVmQCoVPRLIeuduOU1gWP46EZtQrbW4eygb95gcnC8EcSjezJHgtv7pi4fUITlAGK7YPrBi3wy5hlrMGhZdnAyIXx1OKQvsefiTlnIajPKdU+ZvRBu/Liweo2MdR3/qfXbSkNpFC+dgx3nauNiNEqaq41kp+dsFi2HRcklzuqaRISvlFUx0nsd61REXfn/6ZWr7IFKY3qanNKY+CgPwwECngXlAPqZ3YKT1OnQO7gvAOT4BgRzt0TdEVWJsUsB8HsDnZPbNHQ1CWSnzVfpb2Ux6XBePDmPI+L1mieFU5PRF4+V7SESA21Xp3DP/s2uKTSMODZJ0jLBK0kR8EV/SImA7rp4nW5XfOQ0/6u4RWoBDvhpeGmPjP59FaPVeYiggln9A/kTyM+uu+KKlr7rEn5bKw8LHT2KaQS5U8YxDaIXws5t5P5S1ARhL9izCmfxJSPQg5X8wJDe3+1lMK0+wjkboVIn4aXPTnnD9OTW4l52vSepyOSBJgo8l+ZL328/db9LP/JbFWf4eQYVhch+VBF/Aq//t343DBRnq7mtSAXrBxO6TQXLmCCr4Gf5H4umI/DwyYcsKdrfHVhCUM2XgiVS0xd4LzdxNx86Z+EH6a04I+rinuI0kYCS53D/oEiG9b/hB29Q385QXIA9vPjmoGkrFQsDNqT2N3jo9F6tLH/2FX86Fa1Ly/QvxBg05nGZvPhqZbqsy9H7NjOyeMgS2RxjPgAEdV5sIaVfPhaxyDlk7KgaWZlpqpv5fRmbUGGyNBlggSvqlLcmK+hfVpNJs/Rnw93Co1ZEr2+zDsU/0UqEJqqCV8DIaDOClzCw6Q+DYpZ6peZLj4yR65KNR2KFt3s9sqBSx5mY1wdVMa7WLL3mO1h7uSaP4la34qXRZ93Opg4nZ0Q88ZVLbjyqLtcZO/4FHFUyrXnQMiGePq2b9vHNK+aoxn6S+Km4Fqkpz2EvOmA=,iv:3jZ6RfAvhfggQrp19jIIETBVizm4cHBVYDbypBn6MaE=,tag:wGfb1K2kdO94zwIFvIVc9Q==,type:str]
  NORDIGEN_ID: ENC[AES256_GCM,data:omK2GuPEEvUsueyrQ38qeFFd+77Uq3z2fveFSQzrHA==,iv:JmreOACCiGgzGEB49vJcxMsXwBn6NrNK/6Goaw1CGVo=,tag:WY8URilMq2C9feLZHhnV6Q==,type:str]
  NORDIGEN_KEY: ENC[AES256_GCM,data:WvmLJYVMIAV0tV7g0ONKJH+mqO+JBQHi+VjfJkOo1g==,iv:lhPs62ySnaQxk+DtS2rzKWJvB8hiOY7bcCxYY/qa0as=,tag:hmAL+oda0VZv6rM3RFWDpA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ3dmVDV3bVJRWDd0eEo0
        THpnYit2TGtHdEdsN094R0p6Ny9NSDF3Y0g0Ckd5ZTR5OGlUUXlvRjBlU1ZTeXJi
        SkFjVHB2OXJJNU04Njc5UmdXc0M5U1kKLS0tIFFPUENLemtzWDZMR0pvblBBeG5n
        RTAwRXQxNlYxNVV6TTV4NmpiNlphNzAK6Q1UeV9mwRdT6VQFBefsqEjsc2rQ57zD
        vG6RMexIBBeZ1LW7TBbRwQVx/lTRlPeWAU+UtM0m0UXprZJXm4mmFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-15T15:52:10Z"
  mac: ENC[AES256_GCM,data:30ST2Xa8H+/xqKNiN+XWKaSnQ0EotgLN+LxgIyHJ+H3+tgue3+MCboCWPLjFNtkwIgc0GNH0oG97pADi/z6GR0ohaMc/dtF+L5d0VSBHnW4w++Cnru+ikmK+fPp4V6kV6XkG8q4em7PX6HRpJCuCkKgxIPjixXD16QpTZT7huko=,iv:rWDPkuykt/32x5TjTfqjjAs7Hz7HkwdiSVXlDHwOnsQ=,tag:Qiv/qV5c2vkBJMubJFOL0Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
