apiVersion: v1
kind: Secret
metadata:
  name: beta-secret
  namespace: code
type: Opaque
stringData:
  #ENC[AES256_GCM,data:qUyHrjjWt09nojpaO+jqeCBGkB1rr7liZ9jnV3hj5bphFdYSdayTvWWLPw/QaUUfoJ6H3exSCInrJZKyQ6pOCZ4F,iv:d+ErrBVWQdSHsNtnuWEXGAY+A9XrdEZzPKby5hKUidc=,tag:FP7/gosf4KsjBP05tDyvUA==,type:comment]
  T3_SETUP_KEY: ENC[AES256_GCM,data:5JV6jwBmy9TYvyqylSKGsVMW52llLRbyezxEyrdySyQnhm9x+d9zULgrNt8PuOCn,iv:KIOETLBZklODIfjcoSQ/5HIGWfCbiAIqn2HKXO2Omjs=,tag:DGkJ3rwSKxG7LR/0Tr0BcQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVk5JZzdmVElSa3lBZlJp
        Q0NyKzhTRFF6SmVvNFJXcVV6NWRXU0ZpZGhRClp5cWt2S05VYlRTYXVWQU9oM2JG
        c3IrNXhCNXZuR1Jad3phT2x1cUhUeXMKLS0tIGZHbEVqMWVxQTFXRFVwVFl2MWp4
        NlhFMjhaeGUwYit1Zy9ydVBpME5iNW8Kssx4IVWtAYm+ChhlcwETbhFxDTlwfzuy
        3N0yH7taKwoh26DaKevtJLRmuJ0utpc36CYFfjhXHNtoKBvQPyOQow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T16:29:11Z"
  mac: ENC[AES256_GCM,data:7KP9qIQ4qoODdZZ/UHjkVhb+0cNJ24afd4SymOwcbUS3yBr8nLiXqTUVR+J4Hxx96qMFt8r6wR704Y+5pyGTZamvsektXAjkf/vjkAqZPcj0KQFPwgJTuw9K044/JqRIC8hmuYzQXziNkUIvJq2ZEifnAcxsyzoze83qnIfSF5Q=,iv:Cifj9pzbjflIAkKYG2lgZ7BQ4x3hJHHvj4ELRViZm/Y=,tag:hQ7APFyZ+xQ2wOZY0ZJXmw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
