---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap-guest-proxy.yaml
  - ./helmrelease-server.yaml
  - ./helmrelease-ml.yaml
  - ./httproute-external-root.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
