---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neatplan-data
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10Gi
