apiVersion: v1
kind: Secret
metadata:
  name: neatplan-secret
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:YMMlzeG62cDZLLsxQmwE5kIkn16XthiMbb54oRB6+bTYxwcv9t/Jq+8jXiMXVNTDkaUDGfU5lOU/BNYlZECSLBuXe3bjhlppzHk9ENYP1mhURKG4p+gM3xfbsyLOaSV3/3OXqvXxGvZS9HcYsyOgIqxr1c1EQn/3cnseKgdrGo2CIlygd8DzAJD2pfuf3WZmMiVU+g6mwzBLk4QJmP5DnaEJ9Q==,iv:ZsydF+H2myTB6n0aaNAAAxbfoldda/qRRBa9wP/0DNw=,tag:X5/OFcXEX6xLDwSBG4xskg==,type:str]
  NEXTAUTH_URL: ENC[AES256_GCM,data:4Ozo9INslGV/+HnmVYgXIp1hoys=,iv:p8nev0th8GSu8aIsldAY51M1WsY+5Vq5wv2BzOm4n+8=,tag:+kvEVz6CSbGJGq7+FmTXGQ==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:iMnyL9g7469goY9tnxnRy0UbAbZeyNvDBN2xby+PrO/889E5OT/WEA7AgYsYp3H/Ncmz5KJjH97WaobmxjfFOw==,iv:tfJzHN9+eMBRHojMM9mLhl1g3fO/nJ2v0AKsLD6MObo=,tag:N3JZ3VP9odsYEcJDtn1b/A==,type:str]
  NODE_ENV: ENC[AES256_GCM,data:3jBia1HtpLoN1w==,iv:A3hnM+8acHMdQ16M+5r6WaJm8Jm1GWoEAB+U80PRZrs=,tag:64wkf5DGR8387Isu5DHsOA==,type:str]
  CRON_SECRET: ENC[AES256_GCM,data:vVsZddqB+pePk8plB0gtuas8gb5f4trtt1JGGYDJrNdoEX2+Q2UE4jPMAIgZeSldRSmZXqGgnnOYe+9ucmaBmA==,iv:WF1bb0Lx2fVVaVeS1qY0+QkP17YyPL4mqz8zB4aD4FA=,tag:GtEPylZbIWYWLWtmpVMlxg==,type:str]
  CORS_ALLOWED_ORIGIN: ENC[AES256_GCM,data:WCmgyp4RLy+fanMriGyZUkRHGuk=,iv:pUhEUq72PkbBOvSpEltu0l5D+L03i8Sfk+OoJRzmp/M=,tag:kR1CuvQDPiX9K63CDIOx0A==,type:str]
  NEXT_PUBLIC_APP_BASE_URL: ENC[AES256_GCM,data:mWhpWAtcNTVycAfq8LgzQ7fblis=,iv:qpE9jLwm0JkqsF2oMAwM4/4UG5wqHnmAC1CcMolh6XU=,tag:NL2V3C3ikQeN1UALiD+/1Q==,type:str]
  VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:geUIRJsGDhySXwtudByG9/EedKqWSuQQSwB5TXBJKLYd5/FVHvk9KrQZnwIVrjg/zUZ3yGLYmo5qZNAJXBWpyU8FdLQaJkDwpABm+O9PrnY+2Ua+6d3t,iv:XbugdLNPgYHX1zjSlwxHr+qAkbLzQLmOvM6bslWHLDU=,tag:hjLQaS5i/78/Zfx7jde2Mw==,type:str]
  VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:r4OWDatacTP6hlLZ/LwLYqxcff6B+0j8N3xE0vrvKYwlwKLPdzGa8gpLvA==,iv:qLuidl+HyuIVeRprnYTRdl4NV/g/vgxZUAZLfjA1WyA=,tag:YCro56QVVSbACFjRf7C2mQ==,type:str]
  VAPID_SUBJECT: ENC[AES256_GCM,data:ke+s74TwrJILZvvHKclmHrRWue8=,iv:V/YZI3bTXqE44eMguQ19/K6tlWDY0kxLAXpXH19doww=,tag:JWDscjlKRI+WNVZbIkY0gA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb0crdmJ6dXJNTmxmUE50
        WmhoM2VXQWtVUVo2bENuRUZicndXS1dGbFRrCm4vMUhSejlZQ0RScXRuMGU5NENB
        SkpVTVVHZmsxZzhneDl1SFFseFl3Zk0KLS0tIFVWOU5TTkY4WEszczhmVitsNU5U
        UERxa3lRVDMxWjRlZloyU25CcGd6WmsKTzu1YOCbXPpBO1wzgsrGZIhn0oMNADuO
        D22UYSt4Dl/dROHvECWzeRg22NFx+2E6Kc0wb9AlrHAuyPSg8KBi3g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T23:20:26Z"
  mac: ENC[AES256_GCM,data:3Ggt78TrMYMqll2bHdFlUtpcNzVW3rDj7wlsfzmhNRc5UJy7B5vQWwzX5VRbHUw+ABbVfxtYio31+y6yAwbd+e439JRqov4vuzIT4bjXgXOx/athb1dj1pS4mFJqXwvItdcrBnucj9L0VCukTYrnoaKvl3GXXbVHZUKgc2C5wcc=,iv:RZHtANgGM2qjufa3Te56GwD1eXxx2w5/2Rol0/W9Wro=,tag:Y1I6z9+N3oy8bDb0f9cXvQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
