apiVersion: v1
kind: Secret
metadata:
  name: tailscale-router-secret
  namespace: network
type: Opaque
stringData:
  #ENC[AES256_GCM,data:/oVjM/Q962OHgAiMs2kRthN7EE8ZZvkSh2Eld45pUPi4ux5ZDTs/AtapZ2XMaNdFMzPAC6oExod0dP79bR7iyN8FvVLE+P6PSw==,iv:YWdVQxfVaJWkr+6N/fwO0MWOCp3oihRDaLMxD/rFalM=,tag:MopE4FAO8erPGsqpIux8YQ==,type:comment]
  #ENC[AES256_GCM,data:rqZBM7lnxBHi7LtaO6t9IExugo3x9489NC3EFlDvuaTfb28XPrduCRfY8ylWQCDilgS8uTtcjZQKKYHjf1jWMJGT,iv:N6QmNTKTycP0/GOIwb+o3z99wOrz/I9VvUhb/5tZgbg=,tag:XFIvLaAbBFyu7qvct55BqA==,type:comment]
  TS_AUTHKEY: ENC[AES256_GCM,data:OXqSUAJ/aT39qmLds+xTjedc6U3l2K2pijBaXvSexSVTMsx1wxeWPynrtgNyM3LCg5TB0UEhveWAlVcO8i8kpojczXCOfpihCSA3BOA7qPL65eOxPf+1BQ==,iv:4R701vWPeyjo6RxXoOTHef2ZVMCij6qD3iOPApXjVsQ=,tag:5PWm7dzJH8rxAAxeu40ahg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMFJkQndTYUhkcGxYd3lx
        a2N2alE5Z1ltNFlTMWh2cG1zYndaUGRvZUhRCkVoSDBxTXkzUGlmL0psWDhaend6
        SCswOHQwQ0pOcGxqQjB1b1lKTVhKMDQKLS0tIGZTQnp1RzRndUNQa2QwT2d1UU5Q
        OVVBS2NmZHgrbzZVaGFxcWsrKzhOak0KC1iqAbB02xoNj/ZheEJ9s/ctJJBH3nb8
        c/cgaTrjpnN0h3n+ApKDVqywlp5F43r/iGT5JxGuhlHkWT5Eudpjww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T17:20:38Z"
  mac: ENC[AES256_GCM,data:VCsjSyoYLFBrbCCWF4COoRBu/oSUbQ75JdgWd71zxm04c7UtbBOPlfqlV4X0IE1dbnCOz0vqgznKTm+1sG5DS0Dc27B7k4doCLYNm09dj4IEMh6C6qbOxGKUu3eOWTyVB6os3U5ho2uh3nyfRY0mJJTB9JDxWePqhz3bRz0sV1E=,iv:Ye2K512nRxtn4hwFILh1dOqTCbCmKj3a2rRUJh4RcGQ=,tag:62MV9DoygDCBkCMvLJLa9w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
