apiVersion: v1
kind: Secret
metadata:
  name: seedyn-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:HhHXMlqm5L0rp0jdMr6G8ezTN7ybEqDK5rTVzh96TH0Hdecd/aLfSs90+em1f20o/jgN9s6hkF7nhePiA6ZWzCG9wLQtFNCnShbSmni1TFFQMYPhmEytvf+VwF1dsyrDbQhsCbHo+jzaFx8N3kfa2Ho5MsDN,iv:CK2JWuu5ndCT+B39fJNxQ09eNa1uovFSXYW40g6B1tg=,tag:ZuHpc+5QddKRUkPEWOXvEQ==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:vdt/EsZERa0+zRk5BUabPBrLd0wOxXsiw9kMAq3fvDfNuHJ0OkkZUL/83tP+dIaRb8kzACZ8y6ecX1sv6Q==,iv:hhXXo6xVbyqWrJ5oWYGUaZLca7J9wz60kUa4c1pNszM=,tag:BsYz8MFdEFO9LrGdh+op8w==,type:str]
  MINIO_KEY_ID: ENC[AES256_GCM,data:FRTR6sMR,iv:7Fb/ADjLFAvQgKm4WG10dgWfr/itSRn4V62KGHWc0AM=,tag:fkPXkeKhhfTRVTA7qogk+w==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:L7rZ9D3Kmy9arhiXB8/KBoIUG2dyoaOs992Iw6y3c965Xd+n/C/wIpolsc2+38tw,iv:hQZhGNQQdthTqFHi4R3nfoi+Xytg3ufcX+pXSsORl38=,tag:RXKudZjh1SXAmQc8kvNCAQ==,type:str]
  AUTH_SECRET: ENC[AES256_GCM,data:m83Liz/xKypOEaS0DPj1P/BcPIvMSL3uTcrRONmfnxh4AB4zdKPfaTLQZZQ=,iv:5A/DmlpjPD2sidrQQjsIt7dY+q2ubBS4WGaaA8EJkos=,tag:Nm8+JD/xZehE2cRGPCqtaA==,type:str]
  S3_MASTER_SECRET: ENC[AES256_GCM,data:c2ChcQJmO7ML+biLW6nNC4VgUKV2P/KiKbsu3szf0lYaIIhAW4kMvEShH2NzqA7XC5eRFECmXxHKkz56wu4sUw==,iv:XjNzD5jcT04zlNSPpWjwRS7IoqgTwRTNJoLkdwa5xPA=,tag:6BSOCAq4Kr7B5NJiJLsbvg==,type:str]
  AUTH_DAVIDAPPS_ID: ENC[AES256_GCM,data:kVrbfbh9UjJLiVVQPpiqyrqsQ4LCNFJDDJburN0gGy9hv7TbN4eGmQ==,iv:IuWUvAMjPxZT1KEco3Y9y5vji81BOE1X0VMx8mMJmrE=,tag:krHNk5lm/mqZxfnb0Fppaw==,type:str]
  AUTH_DAVIDAPPS_SECRET: ENC[AES256_GCM,data:ahXpcy+RYPHLqqMpU1PDedyNc87GLkUhDLKSYWPs/TMzXup7DJvnoMH9zK5wt7hrkX05d4R/qz08gmmU8oScRdgQV2mXqO+Mc7WsPMrYFkZlwJoI7nBO22Ooqw7Rz6YnM5LUL7FEPewrMQujlqiWDMVbjU8ZaSp1a6ItReqnifE=,iv:az5UEkdUX9LuoBJWSiJdcrNgEK0uzubujMmxN4r8RYo=,tag:FJSAQUPxlancW0qyhiJ4ZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cDVPVnovc3lwV01DRzBs
        TTErbzkxcmcwQTBidVBBVFg0WUUzaTZUeDBjCjNhL1FRRkNKczlDL0FVTTVibWdP
        bGxHWnhPdlFDYWF3NUVWYUx3WkVwSFEKLS0tIGMrQzhENVhuS0NxMktIcW9qbHhr
        bXByVU1qL3VaejZhVWhTNkdYQ2tEajAK5/eBUG+mEu2HhIwnllZuLtwxwo2RYomi
        SJNqZSiENAoq+TFxERETuv6V+xrZshhnWLkOrgoHAHfbW8zlLMQqkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-17T22:27:51Z"
  mac: ENC[AES256_GCM,data:VbISvhTFkbdD7CnPnoVEjilV6BiihPG1PxVQ7mHXMGp7dae2C8W8WTsK0AMgCyfQWough9zXOxU7fblNoY6Vbi6zZCnDG6tZMo6PdKPpZaC3hKWHRwhMvmdZZrsoULqpl2kmRzeF479ZjwkWqkvmRJBLckRKpqKeLOiMPGFBg8Y=,iv:HEOBHlmUVtytwtAJuk4M5PSdH0UbifR4svgl2KF/mkk=,tag:yEH0QQpUEe1dMEuroXou2Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
