apiVersion: v1
kind: Secret
metadata:
  name: gamma-secret
  namespace: code
type: Opaque
stringData:
  #ENC[AES256_GCM,data:P0W0OhZfB4ycqr0lTWTYrAde8kdH2vmpKyrTiZSaedkL3nNOhhyBGzdAvwKOYdqpRgL9JneE/mAVwh2hYLp79DS9qg==,iv:k/CrFE42LWkGOxxKAAlXu6WefYzS/1cEJRbQQDbuYT8=,tag:PlC5rygrMnWlhQlrq+YlTQ==,type:comment]
  T3_SETUP_KEY: ENC[AES256_GCM,data:F+Joxrn8P3WhSO9aSGMAqs8vZNLIRKESj5BSAaI9/gf8+W3q11kGPl3BaHpR12Rd,iv:anNVHdJlCgcD2TK+2UThdnWr44+ujBrPQlbhvoT6nfk=,tag:iOiX/tSQIZYCmtXXlHOZ/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TjJ2UW1TMFB5SzlqaE9O
        TDltam94ZFZYV05aRXNLUXR4UlNleWJhb0Y4CmwvMk95dDRjNnFLNktkNWVQYVlm
        UGJlUUJzWWlLbjZhTi8yTWlza0J6eEUKLS0tIHEyRWRwNnMvL1FHWFp0ajRKMnlv
        SitxZThDVDRSWG84WmdXVHNGMFprYlkK0QxtxMEZlYeeZTS0OKG2IE+LCc0Z1yLn
        EXS6ZF/IWi4qYTQbfKz/Bf3BRL7T1cAFbOSwMkTSr8fMfXgO2Qxu8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T16:29:11Z"
  mac: ENC[AES256_GCM,data:WrzBpDL4rE0N6fS4vI+TSsITAXgb2Z7uaiABXS+zfodfOn2tl3qikRxDXz8PukjT8odex/pp76uwRXiANVwhhLulXNUhyDqnIPUjXM8I5rsshr2uHfVmE6PSw+vb6s/1c1ZeDOqx7n9qzlFuLuG0TYpjmY1fn5JTpA014R92+R8=,iv:W/PjbygYlq4pNeV9/2jIBdtjcHBwmz7CqHpHBoX7ILY=,tag:XSaxJqf5aZBVZ+nnBau4hA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
