apiVersion: v1
kind: Secret
metadata:
  name: baywatch-secret
  namespace: monitoring
type: Opaque
stringData:
  BW_TOKEN: ENC[AES256_GCM,data:OFAF1ABQYEBR7H7vqj+5m9/XGfzsRZs5Iprr+W4y9L3CgvsCpmWRUDURL2/qm82g,iv:TkNooyWCgEvt8yBNUd60lyGmZf7/KM6NNeRJw+lFXCI=,tag:5haiPD51d9Z4P6UNZ2YpLw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQUpEeXhyN210RWlwVjVC
        ekVlQ2VBblVrV3c1clRGRFptaU1uMUozeDNRCkVveVhHMEdUSmEzVFBZc0VybnJ3
        WmYwUDNqVUg1cFgrTUV1Qms3ejlxOHcKLS0tIG9OMVNVYy9RL2lnUzByd1dpZlps
        Uk1DYzJnMlhwUUxWRmhiZTJudmdkaFEKTVlQrUaZoUCxHTwq4K58vvj8W78r1xA9
        KkamUoLc+jq3HvcjS6CmqDlUTK4PgNVPREqwQgoTcfsWDiOxddHqbQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1eer8sfrzmafe78ts498r449cu709g500zfw4pemhptac8rqpwq9qkxm0yq
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-26T19:53:31Z"
  mac: ENC[AES256_GCM,data:1/gw+73cLmk2qBMEYD9IUQt9vI2uQ1pWJD/1teH3R3Omvi6MWQfelfVF24rbWOfIQBeWR79XBGdGASlNIBY36JalwC4k3ZzoA7dIjlkfSBrNfPfbdeHmo9VXSRxQShVYhsOi7SbLaRQuDMxW9Rk/G6dfuAr5hpliWf0J6dMPpsI=,iv:HEaj5lZjrmua9tRWWPFIPtuxWP8A1NSw34v4zR6LN7E=,tag:ag598QFL0NkfQG7KaaD5kQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
